---
settings:
  name: Enterprise applications
  search: ontap-technical-reports, ontap-apps-dbs, netapp-solutions-sap
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 企业级应用程序
    url: "/index.html"
  - section: mssql
  - section: mysql
  - section: oracle
  - section: postgres
  - title: SAP
    entries:
    - title: SAP HANA和AnyDB
      url: sap-solutions.html
  - section: vmware
  - title: 法律声明
    url: "/legal-notices.html"
