---
sidebar: sidebar 
permalink: oracle/oracle-network-config-direct-connect.html 
keywords: direct-connect, oracle 
summary: Oracle数据库和直连ONTAP连接 
searchtitle: Oracle数据库和直连ONTAP连接 
---
= 直连网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
系统管理员有时更愿意通过从配置中删除网络交换机来简化其基础设施。这样可以创建一个更加独立的解决方案，所需组件更少，占用的机架空间也更少。根据所使用的协议，存在一些重要限制。



=== 光纤通道

从 ONTAP 9.19.1 开始，使用特定存储系统 FC 适配器的传统 FC-SAN (SCSI) 和 NVMe/FC 均支持直接连接 FC。HBA 将建立标准点对点 FC 连接。

在 ONTAP 9.19.1 之前，ONTAP 存储系统需要 NPIV，这意味着存储系统必须连接到也支持 NPIV 的 FC 交换机。



=== iSCSI和NVMe/TCP

使用iSCSI或NVMe/TCP的主机可以直接连接到存储系统并正常运行。原因是路径问题。直接连接到两个不同的存储控制器会产生两条独立的数据流路径。丢失路径、端口或控制器不会阻止使用另一个路径。



=== NFS

可以使用直连NFS存储、但有一个重大限制—如果没有大量的脚本编写工作、故障转移将无法正常工作、这是客户的责任。

直连NFS存储的无中断故障转移之所以复杂、是因为本地操作系统上会发生路由。例如、假设主机的IP地址为192.168.1.1/24、并且直接连接到IP地址为192.168.1.50/24的ONTAP控制器。在故障转移期间、该192.168.1.50地址可以故障转移到另一个控制器、并且该地址可供主机使用、但主机如何检测到它的存在？原来的192.168.1.1地址仍然位于不再连接到操作系统的主机NIC上。发往192.168.1.50的流量将继续发送到无法运行的网络端口。

第二个 OS NIC 可以配置为 192.168.1.2，并且能够与故障转移的 192.168.1.50 地址进行通信，但本地路由表将默认使用*且仅使用一个*地址与 192.168.1.0/24 子网进行通信。系统管理员可以创建一个脚本框架，用于检测失败的网络连接，并更改本地路由表或启动和关闭接口。确切的步骤将取决于所使用的操作系统。

在实践中、NetApp客户确实使用直连NFS、但通常仅适用于故障转移期间IO暂停的工作负载。使用硬挂载时、暂停期间不应出现任何IO错误。在服务还原之前、IO应挂起、可以通过故障恢复或手动干预在主机上的NIC之间移动IP地址。
