---
sidebar: sidebar 
permalink: oracle/oracle-dp-data-availability.html 
keywords: data protection, availability, takeover, giveback, switchover, switchback 
summary: 借助基于ONTAP的Oracle数据库最大限度地提高可用性 
---
= 使用ONTAP可获得Oracle数据库
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP旨在最大程度地提高Oracle数据库的可用性。本文档不会介绍完整的ONTAP高可用性功能问题描述。但是、与数据保护一样、在设计数据库基础架构时、基本了解此功能非常重要。



== HA 对

高可用性的基本单位是HA对。每个对都包含冗余链路、以支持将数据复制到NVRAM。NVRAM不是写入缓存。控制器中的RAM用作写入缓存。NVRAM的用途是临时记录数据、以防止发生意外系统故障。在这方面、它类似于数据库重做日志。

NVRAM和数据库重做日志均用于快速存储数据、从而可以尽快提交对数据的更改。直到稍后在ONTAP和大多数数据库平台上的一个称为检查点的过程中、才会更新驱动器(或数据文件)上的永久性数据。在正常操作期间、不会读取NVRAM数据和数据库重做日志。

如果控制器突然出现故障、NVRAM中可能会存储一些尚未写入驱动器的待处理更改。配对控制器会检测到故障、控制驱动器并应用NVRAM中存储的所需更改。



== 接管和交还

接管和交还是指在HA对中的节点之间转移存储资源职责的过程。接管和返回有两个方面：

* 管理允许访问驱动器的网络连接
* 驱动器本身的管理


支持CIFS和NFS流量的网络接口配置了主位置和故障转移位置。接管包括将网络接口移动到与原始位置位于同一子网的物理接口上的临时主端口。交还包括将网络接口移回其原始位置。可以根据需要调整确切的行为。

在接管和回放期间、不会重新定位支持iSCSI和FC等SAN块协议的网络接口。而是应使用包含完整HA对的路径来配置LUN、从而生成主路径和二级路径。


NOTE: 此外、还可以配置指向其他控制器的其他路径、以支持在较大集群中的节点之间重新定位数据、但这不是HA过程的一部分。

接管和返回的第二个方面是磁盘所有权的传输。具体过程取决于多个因素、包括接管/还原的原因以及发出的命令行选项。目标是尽可能高效地执行操作。虽然整个过程看起来可能需要几分钟时间、但驱动器所有权从一个节点转换到另一个节点的实际时刻通常可以以秒为单位进行衡量。



== 接管时间

在接管和备份操作期间、主机I/O会短暂暂停、但在配置正确的环境中、不应发生应用程序中断。I/O延迟的实际过渡过程通常以秒为单位、但主机可能需要更多时间来识别数据路径中的更改并重新提交I/O操作。

中断的性质取决于协议：

* 在过渡到新物理位置后、支持NFS和CIFS流量的网络接口会向网络发出地址解析协议(Address Resolution Protocol、ARP)请求。这会导致网络交换机更新其介质访问控制(MAC)地址表并恢复处理I/O在计划内接管和移交的情况下、中断通常以秒为单位进行衡量、在许多情况下、无法检测到。某些网络可能较慢、无法完全识别网络路径的变化、而某些操作系统可能会在很短的时间内排队等待大量I/O、必须重试。这会延长恢复I/O所需的时间
* 支持SAN协议的网络接口不会过渡到新位置。主机操作系统必须更改正在使用的一个或多个路径。主机观察到的I/O暂停取决于多个因素。从存储系统角度来看、无法提供I/O的时间段仅为几秒。但是、不同的主机操作系统可能需要额外的时间才能使I/O在重试之前超时。较新的操作系统能够更快地识别路径更改、但较旧的操作系统通常需要长达30秒才能识别更改。


下表显示了存储系统无法为应用程序环境提供数据的预期接管时间。在任何应用程序环境中都不应出现任何错误、接管应显示为IO处理中的短暂暂停。

|===


|  | NFS | AFF | ASA 


| 计划内接管 | 15秒 | 第个问题 | 2-3秒 


| 计划外接管 | 30秒 | 第个问题 | 2-3秒 
|===