---
sidebar: sidebar 
permalink: oracle/oracle-tiering-retrieval-policies.html 
keywords: tiering, FabricPool 
summary: Oracle数据库和FabricPool检索策略 
---
= Oracle数据库和FabricPool检索策略
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
分层策略用于控制将哪些Oracle数据库块从性能层分层到容量层。检索策略控制读取已分层的块时发生的情况。



== Default

所有FabricPool卷的初始设置为 `default`，这意味着该行为由`云检索策略控制。`具体行为取决于所使用的层策略。

* `auto`–仅检索随机读取的数据
* `snapshot-only`–检索所有按顺序或随机读取的数据
* `none`–检索所有按顺序或随机读取的数据
* `all`不从容量层检索数据




== 读取时

正在设置 ... `cloud-retrieval-policy` 到读取时会覆盖默认行为、因此读取任何分层数据都会将该数据返回到性能层。

例如、某个卷在下可能已长时间使用不多 `auto` 分层策略和大多数块现在已分层。

如果业务需求发生意外变化、需要重复扫描某些数据以准备特定报告、则可能需要更改 `cloud-retrieval-policy` to `on-read` 以确保读取的所有数据(包括按顺序读取的数据和随机读取的数据)都返回到性能层。这样可以提高卷的顺序I/O性能。



== 提升

提升策略的行为取决于层策略。如果此层策略为 `auto`，然后设置 `cloud-retrieval-policy `to `promote` 在下次分层扫描时从容量层恢复所有块。

如果此层策略为 `snapshot-only`，则返回的唯一块是与活动文件系统关联的块。通常、这不会产生任何影响、因为只有数据块在下进行了分层 `snapshot-only` 策略将是专门与快照关联的块。活动文件系统中不会存在分层块。

但是、如果卷上的数据是通过卷SnapRestore或文件克隆操作从快照还原的、则活动文件系统现在可能需要一些因仅与快照关联而分层出的块。可能需要临时更改 `cloud-retrieval-policy` 策略为 `promote` 以快速检索所有本地所需的块。



== 从不

请勿从容量层检索块。
