---
sidebar: sidebar 
permalink: oracle/oracle-asar2-config-failover.html 
keywords: failover, takeover, ASA r2, oracle 
summary: 要确保 Oracle 数据库操作不会因这些操作而中断，就需要了解存储接管功能。此外，收购操作中使用的论据如果使用不当，可能会影响数据完整性。 
searchtitle: ASA r2 中的 Oracle 数据库和ONTAP控制器故障转移 
---
= ONTAP故障转移
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要确保 Oracle 数据库操作在这些操作期间不会中断，就需要了解存储接管功能。此外，收购操作中使用的论点如果使用不当，可能会影响数据完整性。

正常情况下，写入给定控制器的传入数据会同步镜像到其高可用性伙伴。在具有SnapMirror Active Sync (SM-as) 的ASA r2 环境中，写入操作也会镜像到辅助站点的远程控制器。只有当写入操作在所有位置都存储在非易失性介质中时，主机应用程序才能收到确认。

存储写入数据的介质称为非易失性存储器（NVMEM）。它有时被称为非易失性随机存取存储器（NVRAM），可以将其视为写入日志而不是缓存。正常运行期间，不会读取NVMEM中的数据；它仅用于在软件或硬件发生故障时保护数据。当数据写入驱动器时，数据是从系统 RAM 传输的，而不是从NVMEM传输的。

在接管操作期间，HA 对中的一个节点会接管其伙伴节点的操作。在ASA r2 中，由于不支持MetroCluster ，因此无法进行切换；取而代之的是， SnapMirror Active Sync 提供站点级冗余。例行维护期间的存储接管操作应该是透明的，除了网络路径改变时操作会短暂暂停之外。网络可能很复杂，而且很容易出错，因此NetApp强烈建议在将存储系统投入生产之前彻底测试接管操作。这样做是确保所有网络路径都正确配置的唯一方法。在 SAN 环境中，使用以下命令验证路径状态 `sanlun lun show -p` 或者使用操作系统自带的多路径工具，以确保所有预期路径都可用。ASA r2 系统为 LUN 提供所有活动的优化路径，使用 NVMe 命名空间的客户应依赖操作系统原生工具，因为 sanlun 不涵盖 NVMe 路径。

强制收购时必须谨慎行事。强制更改存储配置意味着忽略拥有驱动器的控制器的状态，备用节点强制接管驱动器的控制权。强制接管操作不当可能导致数据丢失或损坏，因为强制接管操作可能会丢弃NVMEM的内容。接管完成后，数据丢失意味着从数据库的角度来看，存储在驱动器上的数据可能会恢复到稍旧的状态。

使用普通HA对进行强制接管的情况应该很少发生。在几乎所有故障情况下，节点都会关闭并通知合作伙伴，以便进行自动故障转移。有些极端情况，例如滚动故障，其中节点之间的互连丢失，然后一个控制器发生故障，在这种情况下需要强制接管。在这种情况下，节点之间的镜像会在控制器发生故障之前丢失，这意味着幸存的控制器不再拥有正在进行的写入操作的副本。收购必须强制执行，这意味着数据可能会丢失。

[TIP]
====
NetApp 建议采取以下预防措施：

* 务必小心，不要意外地促成收购。通常情况下，不应该强制执行更改，强制更改可能会导致数据丢失。
* 如果需要强制接管，请确保应用程序已关闭，所有文件系统已卸载，并且逻辑卷管理器 (LVM) 卷组已关闭。必须卸载 ASM 磁盘组。
* 在使用 SM-as 时，如果发生站点级故障， ONTAP Mediator 辅助的自动非计划故障转移将在幸存集群上启动，这将导致短暂的 I/O 暂停，然后数据库转换将从幸存集群继续进行。更多信息请参见 https://docs.netapp.com/us-en/asa-r2/data-protection/configure-snapmirror-active-sync.html["ASA r2 系统上的SnapMirror主动同步"] 详细配置步骤请见下文。


====