---
sidebar: sidebar 
permalink: oracle/oracle-dr-snapmirror-basics.html 
keywords: ontap, snapmirror 
summary: SnapMirror和SyncMirror 
---
= SnapMirror和SyncMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
几乎每个应用程序都需要数据复制。

在最基本的层面上、复制可以是在异地存储的磁带上进行复制、也可以是应用程序级复制到备用位置。灾难恢复是指在服务发生灾难性丢失时使用这些副本使服务联机。

ONTAP提供了多种复制选项、可在存储阵列中本机满足各种要求、从而满足各种需求。这些选项可以包括将备份简单地复制到远程站点、甚至可以复制到一个完全自动化的同步解决方案、从而在同一平台上提供灾难恢复和高可用性。

适用于应用程序的主要ONTAP复制技术是NetApp SnapMirror和NetApp SyncMirror技术。这些不是附加产品、而是完全集成到ONTAP中、只需添加一个许可证密钥即可激活。存储级别复制也不是唯一的选项。应用程序级复制(例如使用Oracle DataGuard)还可以集成到基于ONTAP的数据保护策略中。

正确的选择取决于特定的复制、恢复和保留要求。



== ONTAP SnapMirror

SnapMirror是NetApp异步复制解决方案、非常适合保护大型、复杂的动态数据集、例如数据库及其关联应用程序。其关键值如下：

* *易管理性。* SnapMirror是存储软件的本机组成部分、易于配置和管理。不需要附加产品。复制关系只需几分钟即可建立、并可直接在存储系统上进行管理。
* *精简性。*复制基于FlexVol卷、这些卷是LUN或文件的容器、作为一个一致的组进行复制。
* *效率。*建立初始复制关系后、仅复制更改。此外、重复数据删除和数据压缩等效率功能也会保留下来、从而进一步减少必须传输到远程站点的数据量。
* *灵活性。*镜像可以暂时断开、以便测试灾难恢复过程、然后可以轻松地重新建立镜像、而无需进行完整的重新镜像。只需应用更改后的数据即可使镜像恢复同步。也可以反转镜像、以便在灾难结束且原始站点恢复使用后快速重新同步。最后、复制数据的读写克隆可用于测试和开发。


ONTAP提供多种不同的复制技术、但最灵活的是SnapMirror、这是一种卷到卷异步镜像选项。

如前所述、FlexVol卷是基于Snapshot的备份和基于SnapRestore的恢复的基本管理单元。FlexVol卷也是基于SnapMirror的复制的基本单元。第一步是建立源卷到目标卷的基线镜像。初始化此镜像关系后、所有后续操作都将仅基于对已更改数据的复制。

从恢复角度来看、SnapMirror的关键值如下：

* SnapMirror操作易于理解、并且可以轻松实现自动化。
* 只需更新SnapMirror副本即可、只需复制增量更改即可、从而降低了对带宽的需求、并允许更频繁地进行更新。
* SnapMirror具有高度粒度。它基于简单的卷到卷关系、可以创建数百个独立管理的副本并按复制间隔进行复制。复制不需要"一刀切"。
* 镜像方向可以轻松反转、同时保留仅根据更改更新关系的能力。这样、在发生灾难(例如断电)后、主站点恢复正常运行后、便可提供快速故障恢复功能。只需将所做的更改同步回源。
* 镜像可以轻松断开并高效地重新同步、以便预演灾难恢复过程。
* 在完整块级复制模式下运行的SnapMirror不仅可以复制卷中的数据、还可以复制快照。此功能可在灾难恢复站点上提供数据副本和一组完整备份。


在版本灵活模式下运行的SnapMirror允许复制特定快照、从而允许在主站点和二级站点上使用不同的保留时间。



== SnapMirror 同步

SnapMirror同步(SM-S)是对SnapMirror的一项增强功能、可提供RPO = 0的同步复制。它最常用于存储架构、在这些架构中、只有一部分数据需要同步镜像。

SM-S可以在两种略有不同的模式下运行：Sync和StrictSync。

在Sync模式下、更改会在确认之前进行复制。这样可以保证RPO为零、只要复制正常运行即可。如果无法复制更改、SM-S可以退出同步模式并允许操作继续。这允许在正常情况下RPO = 0、但如果复制目标不可用、则数据进程不会完全暂停。

StrictSync可保证RPO = 0。无法复制更改会导致I/O错误、这通常会导致应用程序关闭。

有关SM-S的完整说明、请参见 https://www.netapp.com/media/17174-tr4733.pdf?v=1221202075448P["TR-4733"^] 以及ONTAP官方文档。新版本的ONTAP会不断增加功能。



== 一致性组

ONTAP允许创建一致性组快照、从9.13.1开始、ONTAP可以将卷组(请记住、ONTAP术语中的卷不是LUN、而是由一个或多个文件或LUN组成的管理容器)复制为一致的组。

SnapMirror复制和中断CG SnapMirror关系可保持卷之间的一致性、而SnapMirror同步和SnapMirror业务连续性都可保持成分卷之间的一致性。

这样、您就可以复制多卷数据集、并确保所有卷都是交叉一致的。此外、这还允许"中断镜像并开始"灾难恢复操作、而无需执行其他应用程序或数据库恢复步骤。



== MetroCluster和SyncMirror

MetroCluster也是一种同步复制解决方案、适用于大规模任务关键型工作负载。复制基于SyncMirror。最简单的一层是、SyncMirror会在两个不同的位置创建两组受RAID保护的完整数据。它们可以位于数据中心内的相邻房间内、也可以相距数公里。

SyncMirror与ONTAP完全集成、在RAID级别以上运行。因此、所有常见的ONTAP功能(例如Snapshot副本、SnapRestore和NetApp FlexClone)均可无缝运行。它仍然是ONTAP、只是增加了一层同步数据镜像。

管理SyncMirror数据的一组ONTAP控制器称为NetApp MetroCluster配置。MetroCluster的主要目的是、在各种典型故障情形和灾难恢复故障情形下、为同步镜像数据提供高可用性访问。

使用MetroCluster和SyncMirror进行数据保护的关键值如下：

* 在正常操作中、SyncMirror可在不同位置之间提供有保障的同步镜像。写入操作只有在两个站点的非易失性介质上存在后才会得到确认。
* 如果站点之间的连接发生故障、SyncMirror会自动切换到异步模式、以使主站点始终提供数据、直到连接恢复为止。还原后、它可以高效更新主站点上累积的更改、从而实现快速重新同步。不需要完全重新初始化。


SnapMirror还与基于SyncMirror的系统完全兼容。例如、主数据库可能运行在分布在两个地理站点的MetroCluster集群上。此数据库还可以将备份作为长期归档复制到第三个站点、或者用于在DevOps环境中创建克隆。
