---
sidebar: sidebar 
permalink: oracle/oracle-virtualization-introduction.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: 数据库虚拟化简介 
---
= 虚拟化
:allow-uri-read: 


[role="lead"]
使用VMware ESX、Oracle OVM或KVM对数据库进行虚拟化是NetApp客户越来越普遍的选择、他们选择对其任务关键型数据库进行虚拟化。

在虚拟化支持策略(尤其是VMware产品)方面存在许多误解。事实上、听说Oracle不支持任何虚拟化、这种情况并不少见。这一概念是不正确的、会导致错失虚拟化机会。Oracle文档ID 249212.1讨论了Oracle环境中的已知问题、并指定了对RAC的支持。

如果客户遇到Oracle未知的问题、可能会被要求在物理硬件上重现该问题。运行尖端产品版本的Oracle客户可能不想使用虚拟化、因为可能会发现新的错误。但是、对于使用公开发布的产品版本的虚拟化客户来说、这种情况实际上并不是问题。



== 存储表示

考虑将数据库虚拟化的客户应根据业务需求制定存储决策。虽然这对于所有IT决策来说都是一个正确的表述、但对于虚拟化来说尤其重要、因为项目的规模和范围差别很大。

存储表示有四个基本选项：

* 由虚拟机上的iSCSI启动程序(而不是虚拟机管理程序)管理的iSCSI LUN
* VM挂载的NFS文件系统、而不是虚拟机磁盘(VMDK)
* 虚拟机管理程序数据存储库


一般情况下、请避免对Oracle文件使用数据存储库。此建议的原因有很多：

* *Transparency。*当VM拥有其文件系统时，数据库管理员或系统管理员可以更轻松地确定其数据的文件系统源。
* *性能。*测试表明、通过虚拟机管理程序数据存储库输送所有I/O会对性能产生影响。
* *易管理性。*如果虚拟机拥有其文件系统、则使用或不使用虚拟机管理程序层会影响易管理性。配置、监控、数据保护等过程同样适用于整个资产、包括虚拟化和非虚拟化环境。
* *稳定性和故障排除。*当虚拟机拥有其文件系统时、由于虚拟机上存在整个存储堆栈、因此提供良好、稳定的性能和故障排除会更加简单。虚拟机管理程序的唯一角色是传输FC或IP帧。如果配置中包含数据存储库、则会引入另一组超时、参数、日志文件和潜在错误、从而使配置复杂。
* *可移动性。*当VM拥有其文件系统时、移动Oracle环境的过程将变得更加简单。文件系统可以轻松地在虚拟化和非虚拟化子系统之间移动。
* *受制于供应商。*将数据放入数据存储库后、使用不同的虚拟机管理程序或将数据完全从虚拟化环境中取出将变得非常困难。
* *启用Snapshot。*在某些情况下、由于带宽相对有限、虚拟化环境中的备份可能会成为一个问题。例如、四端口10GbE中继可能足以满足许多虚拟化数据库的日常性能需求。但是、此类中继不足以使用RMAN或其他需要流式传输完整大小数据副本的备份产品执行备份。
+
使用虚拟机拥有的文件系统可以更轻松地利用基于Snapshot的备份和恢复。虚拟机拥有的文件系统会将执行备份的工作卸载到存储系统上。无需纯粹为了满足备份窗口中的带宽和CPU要求而过度构建虚拟机管理程序配置。




TIP: *Oracle建议*避免将NetApp数据放置在数据存储库上以实现最佳性能和易管理性。使用子系统拥有的文件系统、例如由子系统管理的NFS或iSCSI文件系统、或者将其与RDM结合使用。



== 部分驱动程序

为了获得最佳性能、使用完全虚拟化的网络驱动程序至关重要。使用数据存储库时、需要使用一个虚拟化的SCSI驱动程序。与虚拟化驱动程序相比、超虚拟化设备驱动程序可以使子系统更深入地集成到虚拟机管理程序中、而在模拟驱动程序中、虚拟机管理程序会花费更多的CPU时间来模拟物理硬件的行为。

大多数数据库的性能都受存储限制。因此、网络或SCSI驱动程序带来的额外延迟尤为明显。NetApp客户支持遇到了许多性能问题、这些问题通过安装虚拟化驱动程序得到了解决。在一次客户概念验证中、数据库在ESX环境下的性能优于与裸机运行相同硬件的性能。这些测试需要大量I/O、性能差异是由于使用了ESX超虚拟化网络驱动程序所致。


TIP: *SCSI建议*始终使用虚拟化网络驱动程序和NetApp驱动程序。



== 过量使用RAM

过量使用RAM意味着在不同主机上配置的虚拟化RAM要多于物理硬件上的虚拟化RAM。否则可能会出现发生原因意外的性能问题。对数据库进行虚拟化时、虚拟机管理程序不得将Oracle SGA的底层块交换到存储中。这样做会导致性能结果高度不稳定。


TIP: * NetApp建议*不要以允许交换Oracle SGA块的方式配置虚拟机管理程序。
