---
sidebar: sidebar 
permalink: oracle/oracle-dp-online-backup.html 
keywords: oracle, data protection, hot backup 
summary: 基于Oracle数据库快照的备份和恢复 
searchtitle: Oracle数据库联机备份 
---
= 联机备份
:allow-uri-read: 


[role="lead"]
在备份模式下保护和恢复Oracle数据库需要两组数据。请注意、这不是唯一的Oracle备份选项、但最常见。

* 备份模式下数据文件的快照
* 数据文件处于备份模式时创建的归档日志


如果需要完全恢复(包括所有已提交的事务)、则需要第三项：

* 一组当前的重做日志


可以通过多种方法恢复联机备份。许多客户使用ONTAP命令行界面还原快照、然后使用Oracle RMAN或sqlplus完成恢复。在大型生产环境中、这种情况尤为常见、在这些环境中、数据库还原的概率和频率极低、任何还原操作步骤都由技能娴熟的数据库管理人员来处理。为了实现完全自动化、NetApp SnapCenter等解决方案包括一个具有命令行和图形界面的Oracle插件。

一些大型客户采用了一种更简单的方法、即在主机上配置基本脚本、以便在特定时间将数据库置于备份模式、以便为计划的快照做准备。例如、计划命令 `alter database begin backup` 23：58时、 `alter database end backup` 00：02、然后将快照直接计划在午夜在存储系统上。这样、便形成了一个简单、高度可扩展的备份策略、无需外部软件或许可证。



[[data-layout]]
== 数据布局

最简单的布局是在一个或多个专用卷、LUN 或 NVMe 命名空间中隔离数据文件。存储资源不得受到任何其他文件类型的影响。这是为了确保可以通过 SnapRestore 操作快速恢复数据文件，而不会破坏重要的重做日志、控制文件或存档日志。

SAN 对专用资源内的数据文件隔离有类似的要求。对于使用 AFF 存储的 Microsoft Windows 等操作系统，单个卷可能包含多个数据文件 LUN，每个 LUN 都具有一个 NTFS 文件系统。对于其他操作系统，通常有一个逻辑卷管理器。例如，对于 Oracle ASM，最简单的选项是将 ASM 磁盘组的 LUN 限制在可以作为一个单元进行备份和恢复的单个卷上。如果出于性能或容量管理原因需要额外卷，则在新卷上创建一个额外的磁盘组可以简化管理。

ASA 没有 AFF 系统可以托管多个 LUN 的卷级抽象。相反，ASA 使用一致性组。在许多情况下，单个 LUN 或 NVMe 命名空间可能满足数据库的管理和性能要求。如果需要多个 LUN 或命名空间，则可以添加其他资源并将其绑定在一起，作为成为数据文件容器的一致性组。

如果遵循这些准则，则可以直接在存储系统上计划快照。

*注意：*验证ASM `spfile` 和 `passwd` 文件不在托管数据文件的磁盘组中。这会影响有选择地还原数据文件和仅还原数据文件的能力。



[[local-recovery-procedurenfs]]
== 本地恢复过程—NFS

此操作步骤可以手动驱动、也可以通过SnapCenter等应用程序驱动。基本操作步骤如下所示：

. 关闭数据库。
. 将数据文件 NFS 卷恢复到所需还原点之前的快照。
. 将归档日志重放至所需位置。
. 如果需要完全恢复、则重放当前重做日志。


此操作步骤假定所需的归档日志仍存在于活动文件系统中。否则、必须还原归档日志、或者可以将RMAN/sqlplus定向到快照目录中的数据。

此外、对于较小的数据库、最终用户可以直接从中恢复数据文件 `.snapshot` 目录、而无需自动化工具或存储管理员协助即可执行 `snaprestore` 命令：



[[local-recovery-proceduresan]]
== 本地恢复过程—SAN

此操作步骤可以手动驱动、也可以通过SnapCenter等应用程序驱动。基本操作步骤如下所示：

. 关闭数据库。
. 将托管数据文件的磁盘组静置。操作步骤因所选的逻辑卷管理器而异。使用ASM时、此过程需要卸载磁盘组。对于Linux、必须卸载文件系统、并且必须停用逻辑卷和卷组。目标是停止要还原的目标卷组上的所有更新。
. 将托管数据文件磁盘组的 LUN 还原到所需还原点之前的快照。
. 重新激活新还原的磁盘组。
. 将归档日志重放至所需位置。
. 如果需要完全恢复、请重放所有重做日志。


此过程假定所需的归档日志仍位于活动文件系统中。如果不是，则必须通过使归档日志 LUN/命名空间完全脱机并执行还原来还原归档日志（或通过创建先前快照的克隆，由于在同一主机上创建重复的 UUID 或 LVM 名称，这可能很困难）。这也是一个将归档日志分成专用存储资源有用的示例。如果归档日志与重做日志共享一个卷组，则必须先将重做日志复制到其他位置，然后才能还原整个 LUN 集。此步骤可防止丢失最终记录的事务。
