---
sidebar: sidebar 
permalink: oracle/oracle-app-config-rac.html 
keywords: oracle, database, ontap, rac, disktimeout, misscount 
summary: Oracle RAC超时 
searchtitle: Oracle Real Application Clusters超时 
---
= RAC超时
:allow-uri-read: 


[role="lead"]
Oracle RAC是一款集群软件产品、它具有多种类型的内部检测信号进程、用于监控集群的运行状况。


NOTE: 中的信息 link:#misscount["MissCount"] 第节介绍了有关使用网络存储的Oracle RAC环境的重要信息、在许多情况下、需要更改默认Oracle RAC设置、以确保RAC集群在网络路径更改和存储故障转移/切换操作后不会受到影响。



== 磁盘超时

与存储相关的主RAC参数是 `disktimeout`。此参数用于控制表决文件I/O必须完成的阈值。如果 `disktimeout` 超过此参数后、RAC节点将从集群中逐出。此参数的默认值为200。此值对于标准存储接管和回用过程应足够。

NetApp强烈建议在将RAC配置投入生产之前对其进行全面测试、因为许多因素会影响接管或恢复。除了完成存储故障转移所需的时间之外、传播链路聚合控制协议(Link Aggregate Control Protocol、LACP)更改也需要额外的时间。此外、SAN多路径软件必须检测到I/O超时、然后在备用路径上重试。如果数据库非常活跃、则在处理表决磁盘I/O之前、必须对大量I/O进行排队和重试。

如果无法执行实际的存储接管或恢复、则可以在数据库服务器上执行缆线拉拔测试来模拟这种影响。

[TIP]
====
* NetApp建议*：

* 退出 `disktimeout` 参数、默认值为200。
* 始终全面测试RAC配置。


====


== MissCount

。 `misscount` 参数通常仅影响RAC节点之间的网络检测信号。默认值为30秒。如果网格二进制文件位于存储阵列上或操作系统启动驱动器不在本地、则此参数可能会变得很重要。这包括启动驱动器位于FC SAN上的主机、NFS启动的操作系统以及启动驱动器位于VMDK文件等虚拟化数据存储库上的主机。

如果存储接管或恢复中断了对启动驱动器的访问、则网格二进制位置或整个操作系统可能会暂时挂起。ONTAP完成存储操作以及操作系统更改路径和恢复I/O所需的时间可能会超过 `misscount` 阈值。因此、在恢复与启动LUN或网格二进制文件的连接后、节点会立即被逐出。在大多数情况下、发生逐出和后续重新启动时不会记录任何日志消息来指示重新启动的原因。并非所有配置都会受到影响、因此、请在RAC环境中测试任何SAN启动、NFS启动或基于数据存储库的主机、以便在与启动驱动器的通信中断时RAC保持稳定。

对于非本地启动驱动器或托管的非本地文件系统 `grid` 二进制文件、 `misscount` 需要更改才能匹配 `disktimeout`。如果更改了此参数、请执行进一步测试、以确定对RAC行为的任何影响、例如节点故障转移时间。

[TIP]
====
* NetApp建议*：

* 离开 `misscount` 参数、默认值为30、除非满足以下条件之一：
+
** `grid` 二进制文件位于网络连接驱动器上、包括NFS、iSCSI、FC和基于数据存储库的驱动器。
** 操作系统通过SAN启动。


* 在这种情况下、请评估影响操作系统或访问的网络中断的影响 `GRID_HOME` 文件系统。在某些情况下、此类中断发生原因会使Oracle RAC守护进程发生拖延、从而可能导致出现 `misscount`基于的超时和逐出。超时默认为27秒、即的值 `misscount` 减号 `reboottime`。在这种情况下，增加 `misscount` 至200以匹配 `disktimeout`。


====