= 空间管理
:allow-uri-read: 


精简配置有多种形式、是ONTAP为企业级应用程序环境提供的许多功能不可或缺的组成部分。精简配置也与效率技术密切相关、原因相同：效率功能允许存储的逻辑数据比存储系统上的技术数据多。

几乎任何快照使用都涉及精简配置。例如、NetApp存储上的典型10 TB数据库包含大约30天的快照。这种安排会使活动文件系统中显示大约10 TB的数据、并将300 TB专用于快照。总存储量为312 TB、通常占用大约12 TB到15 TB的空间。活动数据库会占用10 TB的空间、其余300 TB的数据仅需要2 TB到5 TB的空间、因为系统仅会存储对原始数据所做的更改。

克隆也是精简配置的一个示例。一家主要NetApp客户为一个80 TB数据库创建了40个克隆、以供开发使用。如果使用这些克隆的所有40位开发人员都覆盖了每个数据文件中的每个块、则需要3.2 PB以上的存储。实际上、周转率较低、并且总空间需求接近40 TB、因为驱动器上仅存储更改。



== 空间管理

对应用程序环境进行精简配置时必须格外小心、因为数据变更率可能会意外增加。例如、如果为数据库表重新编制索引或对VMware子系统应用大规模修补、则快照占用的空间会快速增长。放错位置的备份可能会在很短的时间内写入大量数据。最后、如果文件系统意外用尽可用空间、则很难恢复某些应用程序。

幸运的是、这些风险可以通过仔细配置来解决 `volume-autogrow` 和 `snapshot-autodelete` 策略。正如其名称所暗示的那样、这些选项使用户能够创建策略、以自动清除快照占用的空间或增加卷以容纳更多数据。有多种选项可供选择、不同客户的需求也会有所不同。

请参见 link:https://docs.netapp.com/us-en/ontap/volumes/index.html["逻辑存储管理文档"] 有关这些功能的完整讨论。



== LUN精简配置

随着数据被删除、文件系统环境中活动LUN的精简配置效率可能会逐渐降低。除非已删除的数据被零覆盖或空间通过TRIM/UNMAP空间回收释放、否则"已删除"的数据会在文件系统中占用越来越多的未分配空格。此外、活动LUN的精简配置在许多数据库环境中的用途有限、因为数据文件在创建时会初始化为其完整大小。

仔细规划LVM配置可以提高效率、并最大限度地减少存储配置和LUN大小调整的需求。使用Veritas VLVM或Oracle ASM等LVM时、底层LUN会划分为仅在需要时才使用的块区。例如、如果数据集的大小从2 TB开始、但随着时间的推移可能会增长到10 TB、则可以将此数据集放置在LVM磁盘组中组织的10 TB精简配置LUN上。在创建时、它只会占用2 TB的空间、并且只会在为满足数据增长而分配块区时占用额外空间。只要空间受到监控、此过程就会很安全。



== 预留百分比

预留百分比是指卷中LUN在空间效率方面的行为。选项 `fractional-reserve` 设置为100%时、卷中的所有数据在使用任何数据模式时均可实现100%的周转率、而不会耗尽卷上的空间。

例如、假设数据库位于1 TB卷中的一个250 GB LUN上。创建快照会立即在卷中预留额外的250 GB空间、以保证卷不会因任何原因用尽空间。使用预留百分比通常会造成浪费、因为数据库卷中的每个字节极不可能需要覆盖。没有理由为从未发生的事件预留空间。但是、如果客户无法监控存储系统中的空间消耗、并且必须确保空间永远不会用尽、则需要100%预留百分比才能使用快照。



== 数据压缩和重复数据删除

数据压缩和重复数据删除都是精简配置的两种形式。例如、50 TB的数据占用空间可能会压缩为30 TB、从而节省20 TB的空间。要使数据压缩产生任何优势、必须将这20 TB中的一部分用于其他数据、或者购买的存储系统必须小于50 TB。这样、存储的数据就会超过存储系统上的技术可用数据。从数据角度来看、数据容量为50 TB、尽管它在驱动器上仅占用30 TB。

数据集的可压缩性总是有可能发生变化、从而导致实际空间消耗增加。这种消耗量的增加意味着、在监控和使用方面、必须像其他形式的精简配置一样管理数据压缩 `volume-autogrow` 和 `snapshot-autodelete`。

有关数据压缩和重复数据删除的详细信息、请参见链接efficiency.html



=== 数据压缩和预留百分比

数据压缩是一种精简配置形式。预留百分比会影响数据压缩的使用、但需要注意的一点是、空间是在创建快照之前预留的。通常、只有当存在快照时、预留百分比才重要。如果没有快照、则预留百分比并不重要。而数据压缩则不是这种情况。如果在已进行数据压缩的卷上创建了LUN、则ONTAP会保留空间以容纳快照。此行为在配置期间可能会令人困惑、但这是预期行为。

例如、假设一个10 GB的卷具有一个5 GB的LUN、该LUN已压缩为2.5 GB、并且没有快照。请考虑以下两种情形：

* 预留百分比= 100会导致利用率达到7.5 GB
* 预留百分比= 0会导致利用率达到2.5 GB


第一种情形包括：当前数据占用2.5 GB空间、而源在预计快照使用时的周转率为100%时占用5 GB空间。第二种情形不会预留任何额外空间。

虽然这种情况可能看起来令人困惑、但在实践中不太可能遇到。数据压缩意味着精简配置、而在LUN环境中进行精简配置需要预留百分比。压缩的数据始终可以被不可压缩的内容覆盖、这意味着必须对卷进行精简配置、才能进行压缩、从而节省空间。

[TIP]
====
* NetApp建议*采用以下预留配置：

* 设置 `fractional-reserve` 如果已实施基本容量监控、则为0 `volume-autogrow` 和 `snapshot-autodelete`。
* 设置 `fractional-reserve` 如果没有监控能力或在任何情况下都无法排空空间、则为100。


====