---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MSSQL,SQL Server,TR-4590, SnapCenter, ONTAP 
summary: 基于ONTAP的Microsoft SQL Server 
---
= 基于ONTAP的Microsoft SQL Server
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
ONTAP为您的Microsoft SQL Server数据库提供企业级安全性和性能解决方案、同时还提供世界一流的工具来管理您的环境。


NOTE: 本文档将取代先前发布的技术报告_TR-4590：《采用ONTAP的Microsoft SQL Server最佳实践指南》

NetApp假定读者具备以下方面的实践知识：

* ONTAP
* Microsoft SQL Server架构和管理
* SnapCenter备份软件、包括以下组件：
* NetApp SnapCenter作为备份软件、其中包括：
+
** 适用于 Microsoft Windows 的 SnapCenter 插件
** 适用于SQL Server的SnapCenter插件




本最佳实践部分的范围仅限于根据NetApp为存储基础架构建议的原则和首选标准进行技术设计。端到端实施已超出范围。

有关NetApp产品的兼容性信息，请参见link:https://mysupport.netapp.com/matrix/["NetApp 互操作性表工具（ IMT ）"^]。



== Microsoft SQL Server工作负载

在部署SQL Server之前、您必须了解SQL Server数据库实例支持的应用程序的工作负载要求。每个应用程序对容量、性能和可用性有不同的要求、因此每个数据库的设计都应以最佳方式支持这些要求。许多组织使用应用程序要求定义SLA、将数据库分为多个管理层。SQL Server工作负载通常按如下所述进行分类：

* OLTP、通常是组织中最关键的数据库。这些数据库通常为面向客户的应用程序提供支持、并被视为公司核心运营的关键。任务关键型OLTP数据库及其支持的应用程序通常具有SLA、这些SLA要求高性能、容易受到性能下降的影响、并要求最大可用性。它们也可能是"无中断故障转移集群"或"无中断可用性"组的候选对象。这些类型数据库上的I/O混合通常表现为75%到90%的随机读取和25%到10%的写入。
* 决策支持系统(DSS)数据库、有时称为数据仓库。这些数据库对于许多依靠分析来开展业务的企业来说至关重要。在运行查询时、这些数据库对CPU利用率和磁盘读取操作非常敏感。在许多组织中、DSS数据库在月份、季度和年终都是最重要的此工作负载的读取I/O混合比例通常接近100%、并且IO吞吐量通常比IOPS更重要。

