---
sidebar: sidebar 
permalink: mssql/mssql-data-protection.html 
keywords: MS-SQL,mssql,SQL Server, SnapCenter, data protection 
summary: 使用ONTAP保护Microsoft SQL Server数据 
---
= 使用ONTAP保护Microsoft SQL Server数据
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
保护数据库对于任何组织都至关重要。随着数据大小和数据库数量的增加、维护恢复时间目标(RTO)和恢复点目标(RPO)至关重要。

数据库备份的主要注意事项是利用NetApp Snapshot技术。应用程序一致的备份和数据库布局是实现可由NetApp SnapCenter协调的RTO和RPO的另一个重要考虑因素。



== SnapCenter

SnapCenter是适用于企业应用程序的NetApp数据保护软件。使用NetApp SnapCenter软件以及适用于SQL Server的插件和适用于Microsoft Windows的插件、可以快速轻松地保护SQL Server数据库。

此产品支持应用程序一致的备份、自动克隆以及SQL Server数据库、实例或可用性组的还原和恢复。


TIP: * NetApp建议*使用SnapCenter创建Snapshot副本。

有关适用于SnapCenter的SQL Server插件的详细信息、请参见 link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["TR-4714：《使用NetApp SnapCenter的SQL Server最佳实践指南》"^]。



== 使用T-SQL快照保护数据库

在SQL Server 2022中、Microsoft引入了T-SQL快照、与数据库管理员不易使用的传统方法相比、它具有内置优势。利用ONTAP REST API、您可以调用命令来创建卷快照。

以下是备份工作流示例：

. 使用alter命令冻结数据库—提供在底层存储上执行一致快照的机会。之后、您可以使用backup命令解冻数据库并记录快照。
. 使用新的backup group和backup server命令同时对存储卷上的多个数据库执行快照。
. 执行完整备份或copy_only完整备份。这些备份也会记录在msdb中。
. 在快照完整备份之后、使用通过正常流式传输方法创建的日志备份执行时间点恢复。如果需要、还支持流式差异备份。


要了解更多信息，请参见 link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["了解T-SQL快照的Microsoft文档"^]。
