---
sidebar: sidebar 
permalink: mssql/mssql-disaster-recovery.html 
keywords: MSSQL,SQL Server, disaster recovery, snapmirror 
summary: 使用ONTAP进行Microsoft SQL Server灾难恢复 
---
= 使用ONTAP进行Microsoft SQL Server灾难恢复
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
企业数据库和应用程序基础架构通常需要进行复制、以防止发生自然灾难或意外业务中断、同时最大限度地减少停机时间。

SQL Server无中断可用性组复制功能是一个绝佳的选择、NetApp提供了将数据保护与无中断集成的选项。但是、在某些情况下、您可能需要考虑使用ONTAP复制技术。有三个基本选项。



== SnapMirror

SnapMirror技术为通过LAN和广域网复制数据提供了快速灵活的企业解决方案。SnapMirror技术仅在创建初始镜像后将更改后的数据块传输到目标、从而显著降低网络带宽要求。它可以配置为同步或异步模式。



== NetApp MetroCluster

MetroCluster配置有助于为应用程序、数据库和虚拟化平台提供高可用性、零数据丢失的存储解决方案。该解决方案将基于阵列的集群与同步复制相结合、为整个存储和主机环境提供额外的保护层。



== SnapMirror active sync (原SnapMirror业务连续性)

SnapMirror主动同步基于SnapMirror同步、它能够将多个LUN复制到副本存储、同时保持写入顺序一致性。使用MetroCluster时、各个站点的ONTAP控制器(包括网络配置)应完全相同。使用SnapMirror主动同步时、您实际上拥有两个不同的ONTAP系统、它们会维护LUN数据的独立副本、但会相互协作、为该LUN提供一个实例。从主机角度来看、它是一个LUN实体。

MetroCluster与SnapMirror主动同步的主要区别在于粒度和可扩展性。如果您只需要选择要同步复制的特定工作负载、或者两个站点都应具有可用于读/写操作的LUN、则SnapMirror主动同步是更好的选择。如果您需要复制整个环境甚至数据中心、MetroCluster是一个更好的选择。此外、SnapMirror主动同步目前仅支持SAN、而MetroCluster支持多协议、包括SAN、NFS和SMB。

有关SnapMirror的详细信息，请参见link:https://www.netapp.com/pdf.html?item=/media/17229-tr4015pdf.pdf["TR-4015：《适用于ONTAP 9的SnapMirror配置和最佳实践指南》"^]。
