---
sidebar: sidebar 
permalink: mssql/Storage-considerations.html 
keywords: MS-SQL,mssql,SQL Server, database layout 
summary: 基于ONTAP的Microsoft SQL Server 
---
= Microsoft SQL Server存储注意事项
:allow-uri-read: 


[role="lead"]
通过将NetApp存储解决方案与Microsoft SQL Server相结合、可以创建企业级数据库存储设计、以满足当今最苛刻的应用程序要求。

要优化这两种技术、了解SQL Server I/O模式和特征至关重要。SQL Server数据库的存储布局设计合理、可支持SQL Server的性能以及SQL Server基础架构的管理。良好的存储布局还可以成功完成初始部署、并随着业务的增长逐步平稳地扩展环境。



== 数据存储设计

对于不使用SnapCenter 执行备份的SQL Server数据库、Microsoft建议将数据和日志文件放置在不同的驱动器上。对于同时更新和请求数据的应用程序、日志文件会占用大量写入资源、而数据文件(取决于您的应用程序)会占用大量读/写资源。对于数据检索、不需要日志文件。因此、可以通过放置在其自己驱动器上的数据文件来满足数据请求。

创建新数据库时、Microsoft建议为数据和日志指定单独的驱动器。要在创建数据库后移动文件、必须使数据库脱机。有关Microsoft的更多建议、请参见 link:https://docs.microsoft.com/en-us/sql/relational-databases/policy-based-management/place-data-and-log-files-on-separate-drives?view=sql-server-ver15["将数据和日志文件放在不同的驱动器上"^]。



== 聚合

聚合是NetApp存储配置的主存储容器、包含一个或多个RAID组、其中既包含数据磁盘、又包含奇偶校验磁盘。NetApp已使用数据文件和事务日志文件分开的共享和专用聚合执行了各种I/O工作负载特征化测试。测试表明、一个具有更多RAID组和磁盘轴的大型聚合可以优化和提高存储性能、并使管理员更易于管理、原因有两个：

* 一个大型聚合可使所有磁盘轴的I/O功能对所有文件可用。
* 一个大型聚合可以最高效地利用磁盘空间。


对于高可用性(HA)、请将SQL Server Always On可用性组二级同步副本放在聚合中的一个单独Storage Virtual Machine (SVM)上。为了实现灾难恢复、请将异步副本放置在灾难恢复站点中单独存储集群中的聚合上、并使用NetApp SnapMirror技术复制内容。NetApp建议在聚合中至少留出10%的可用空间、以获得最佳存储性能。



== Volumes

NetApp FlexVol卷会创建并驻留在聚合中。可以在一个聚合中创建多个卷、并且每个卷都可以在聚合之间进行扩展、减少或移动、而无需用户停机。



=== 卷设计注意事项

在创建数据库卷设计之前、请务必了解SQL Server I/O模式和特征如何根据工作负载以及备份和恢复要求而有所不同。请参见以下适用于灵活卷的NetApp建议：

* 使用灵活卷存储SQL Server数据库文件、并避免在主机之间共享卷。
* 使用NTFS挂载点而不是驱动器盘符、以超过Windows中26个驱动器盘符的限制。使用卷挂载点时、一般建议为卷标签指定与挂载点相同的名称。
* 适当时、配置卷自动调整策略以帮助防止出现空间不足情况。17采用ONTAP的Microsoft SQL Server最佳实践指南©2022 NetApp、Inc. 保留所有权利。
* 当SQL Server数据库I/O配置文件大部分包含大型顺序读取(例如决策支持系统工作负载)时、在卷上启用读取重新分配。读取重新分配可优化块以提供更好的性能。
* 如果在SMB共享上安装SQL Server、请确保在SMB/Cifis卷上启用了Unicode以创建文件夹。
* 将卷中的NetApp Snapshot副本预留值设置为零、以便于从操作角度进行监控。
* 禁用存储Snapshot™副本计划和保留策略。请改用SnapCenter来协调SQL Server数据卷的Snapshot副本。
* 将SQL Server系统数据库放在专用卷或VMDK上。
* tempdb是一个系统数据库、SQL Server会使用它作为临时工作空间、尤其是用于I/O密集型DBCC CHECKDB操作。因此、请将此数据库放在具有一组单独磁盘轴的专用卷上。在卷数量是一项挑战的大型环境中、您可以在仔细规划后将tempdb整合到较少的卷中、并将其与其他系统数据库存储在同一个卷中。tempdb的数据保护不是高优先级、因为每次重新启动SQL Server时都会重新创建此数据库。
* 将用户数据文件(.mdf)放在不同的卷上、因为它们是随机读/写工作负载。通常、创建事务日志备份的频率比创建数据库备份的频率更高。因此、请将事务日志文件(.ldf)放置在与数据文件不同的卷或VMDK上、以便可以为每个卷或VMDK创建独立的备份计划。这种分离还会将日志文件的顺序写入I/O与数据文件的随机读/写I/O隔离开来、并显著提高SQL Server性能。




== LUN

* 确保用户数据库文件和用于存储日志备份的日志目录位于不同的卷上、以防止保留策略在SnapVault技术中使用快照时覆盖这些快照。
* 确保SQL Server数据库与包含非数据库文件(如全文搜索相关文件)的LUN驻留在不同的LUN上。
* 将数据库二级文件(作为文件组的一部分)放在不同的卷上可提高SQL Server数据库的性能。只有当数据库的.mdf文件不与任何其他.mdf文件共享其LUN时、此分隔才有效。
* 如果使用DiskManager或其他工具创建LUN、请确保在格式化LUN时将分区的分配单元大小设置为64K。
* 请参见 link:https://www.netapp.com/media/10680-tr4080.pdf["Microsoft Windows和本机MPIO、并遵循适用于现代SAN的ONTAP最佳实践"] 在MPIO属性中将Windows上的多路径支持应用于iSCSI设备。




=== 日志目录

在SQL Server中指定日志目录、用于在主机级别存储事务日志备份数据。如果使用SnapCenter备份日志文件、则SnapCenter使用的每个SQL Server主机都必须配置一个主机日志目录、才能执行日志备份。SnapCenter 具有一个数据库存储库、因此与备份、还原或克隆操作相关的元数据存储在一个中央数据库存储库中。

主机日志目录的大小计算如下：
主机日志目录大小=((最大数据库LDF大小x每日日志更改率%) x (快照保留)÷(1 - LUN开销空间%)
主机日志目录规模估算公式假定LUN开销空间为10%

将日志目录放在专用卷或LUN上。主机日志目录中的数据量取决于备份的大小以及备份的保留天数。SnapCenter只允许每个SQL Server主机有一个主机日志目录。您可以在SnapCenter --> Host --> Configure Plug-in中配置主机日志目录。

[TIP]
====
* NetApp建议*对主机日志目录执行以下操作：

* 确保主机日志目录不会被任何可能损坏备份快照数据的其他类型的数据共享。
* 请勿将用户数据库或系统数据库放置在托管挂载点的LUN上。
* 在SnapCenter将事务日志复制到的专用FlexVol卷上创建主机日志目录。
* 使用SnapCenter向导将数据库迁移到NetApp存储、以便数据库存储在有效位置、从而成功执行SnapCenter备份和还原操作。请注意、迁移过程会造成系统中断、并且在迁移过程中、发生原因会使数据库脱机。
* 对于SQL Server的故障转移集群实例(FCIS)、必须满足以下条件：
+
** 如果您使用的是故障转移集群实例、则主机日志目录LUN必须是与要备份的SQL Server实例位于同一集群组中的集群磁盘资源SnapCenter。
** 如果您使用的是故障转移集群实例、则必须将用户数据库置于共享LUN上、这些共享LUN是分配给与SQL Server实例关联的集群组的物理磁盘集群资源。




====