---
sidebar: sidebar 
permalink: mssql/storage-efficiency.html 
keywords: MS-SQL,mssql,SQL Server 
summary: 基于ONTAP的Microsoft SQL Server 
---
= Microsoft SQL Server的ONTAP存储效率
:allow-uri-read: 


[role="lead"]
存储效率是指存储和管理SQL Server数据的能力、其占用的存储空间最少、对系统整体性能几乎没有影响、甚至没有影响。

存储效率是RAID、配置(整体布局和利用率)、镜像和其他数据保护技术的组合。NetApp技术(如Snapshot副本、精简配置、FlexClone)可优化基础架构中的现有存储、推迟或避免未来的存储支出、从而帮助实现成本优势。将这些技术结合使用的次数越多、节省的空间就越大。有关详细信息，请参见 link:../common/ontap/thin-provisioning.html["配置建议"]

存储压缩、数据缩减和重复数据删除是其他存储效率选项、可增加给定物理存储量所需的逻辑数据量。有关更多详细信息，请参见 link:../common/ontap/efficiency.html["效率最佳实践"]。

SQL Server还具有压缩和高效管理数据的功能。SQL Server目前支持两种类型的数据压缩：行压缩和页面压缩。

行压缩会更改数据存储格式。例如、它会将整数和小数更改为可变长度格式、而不是其本机固定长度格式。此外、它还会通过消除空格将固定长度字符串更改为可变长度格式。页面压缩可实现行压缩和另外两种压缩策略(前缀压缩和词典压缩)。有关页面压缩的详细信息、请参见 link:https://learn.microsoft.com/en-us/sql/relational-databases/data-compression/page-compression-implementation?view=sql-server-ver16&redirectedfrom=MSDN["页面压缩实施"^]。

SQL Server 2008及更高版本的企业版、开发人员版和评估版目前支持数据压缩。虽然数据压缩可以由数据库本身执行、但在SQL Server环境中很少会出现这种情况。

下面是管理SQL Server数据文件空间的建议

* 在SQL Server环境中使用精简配置可提高空间利用率、并在使用空间保证功能时降低整体存储需求。
* 对最常见的部署配置使用自动增长、因为存储管理员只需要监控聚合中的空间使用量。
* 建议不要在包含SQL Server数据文件的任何卷上启用重复数据删除、除非该卷已知包含同一数据的多个副本、例如、将数据库从备份还原到单个卷。




== 空间回收

可以定期启动空间回收、以恢复LUN中未使用的空间。对于SnapCenter、您可以使用以下PowerShell命令启动空间回收。

[listing]
----
Invoke-SdHostVolumeSpaceReclaim -Path drive_path
----
如果需要运行空间回收、则应在活动较少的时段运行此过程、因为它最初会占用主机上的周期。
