---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: '适用于VMware Live Site Recovery (vrr)和Site Recovery Manager (SRM)的ONTAP解决方案' 
---
= 使用ONTAP进行VMware实时站点恢复
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
自2002年引入现代数据中心以来、ONTAP已成为VMware vSphere以及最近的Cloud Foundation环境的主要存储解决方案。它继续推出创新功能、以简化管理并降低成本。

本文档介绍了适用于VMware实时站点恢复(VSR)的ONTAP解决方案(以前称为站点恢复管理器(SRM))、这是VMware行业领先的灾难恢复(Disaster Recovery、DR)软件、其中包括可简化部署、降低风险和简化日常管理的最新产品信息和最佳实践。


NOTE: 本文档将取代先前发布的技术报告_TR-4900:《使用ONTAP的VMware Site Recovery Manager_》

最佳实践是指南和兼容性工具等其他文档的补充。它们是根据 NetApp 工程师和客户的实验室测试和丰富的现场经验开发的。在某些情况下，建议的最佳实践可能不适合您的环境；但是，它们通常是最简单的解决方案，可满足大多数客户的需求。

本文档重点介绍与适用于VMware vSphere 10.4的ONTAP工具(包括NetApp存储复制适配器[SRA ]和VASA Provider [VP])以及VMware Live Site Recovery 9结合使用时、ONTAP 9最新版本中的功能。



== 为什么要将ONTAP与甚量卷请求或SRM结合使用？

由ONTAP提供支持的NetApp数据管理平台是VLSR采用最广泛的存储解决方案之一。原因很多：一个安全、高性能、统一协议(NAS和SAN结合使用)的数据管理平台、可提供行业定义的存储效率、多租户、服务质量控制、利用节省空间的快照保护数据、以及利用SnapMirror进行复制。利用原生混合多云集成来保护 VMware 工作负载，以及触手可及的大量自动化和流程编排工具。

使用SnapMirror进行基于阵列的复制时、您可以利用ONTAP最成熟、最成熟的技术之一。SnapMirror 可以让您获得安全高效的数据传输优势，只复制更改过的文件系统块，而不是复制整个 VM 或数据存储库。即使这些块也可以利用重复数据删除，数据压缩和数据缩减等空间节省。现代 ONTAP 系统现在使用与版本无关的 SnapMirror ，让您可以灵活地选择源集群和目标集群。SnapMirror 确实已成为灾难恢复可用的最强大工具之一。

无论您使用的是传统 NFS ， iSCSI 还是光纤通道连接的数据存储库（现在支持 VVol 数据存储库）， VLSR 都可以提供强大的第一方产品，充分利用 ONTAP 的最佳功能进行灾难恢复或数据中心迁移规划和编排。



== VLSR 如何利用 ONTAP 9

VLSR 可通过与适用于 VMware vSphere 的 ONTAP 工具集成来利用 ONTAP 系统的高级数据管理技术， VMware vSphere 是一种虚拟设备，其中包括三个主要组件：

* 无论您使用的是SAN还是NAS、ONTAP工具vCenter插件(以前称为虚拟存储控制台(VSC))均可简化存储管理和效率功能、提高可用性并降低存储成本和运营开销。它使用最佳实践配置数据存储库，并为 NFS 和块存储环境优化 ESXi 主机设置。为了获得所有这些优势、在将vSphere与运行ONTAP的系统结合使用时、NetApp建议使用此插件。
* ONTAP工具VASA Provider支持VMware vStorage APIS for Storage Aware (VASA)框架。VASA Provider 可将 vCenter Server 与 ONTAP 连接起来，以帮助配置和监控 VM 存储。这样、便可支持VMware虚拟卷(vvol)并管理VM存储策略和单个VM vvol性能。此外，它还提供警报，用于监控容量以及配置文件合规性。
* SRA 与 VLSR 结合使用，用于管理传统 VMFS 和 NFS 数据存储库的生产站点和灾难恢复站点之间的 VM 数据复制，并用于无中断测试灾难恢复副本。它有助于自动执行发现，恢复和重新保护任务。它既包含一个SRA服务器设备、又包含用于Windows SRM服务器和vrr设备的SRA适配器。


在vrr服务器上安装并配置SRA适配器以保护非vvol数据存储库后、您可以开始配置vSphere环境以实现灾难恢复的任务。

SRA为VSR服务器提供了一个命令和控制界面、用于管理包含VMware虚拟机(VM)的ONTAP FlexVol卷以及对其进行保护的SnapMirror复制。

VLSR可以使用NetApp的专有FlexClone技术无干扰地测试您的灾难恢复计划、以便为灾难恢复站点上受保护的数据存储库创建近乎即时的克隆。VLSR 会创建一个沙盒来进行安全测试，以便在发生真正灾难时保护您的组织和客户，从而让您对组织在发生灾难时执行故障转移的能力充满信心。

如果发生真正的灾难甚至是计划内迁移， VLSR 允许您通过最终 SnapMirror 更新（如果您选择这样做）向数据集发送任何最后一分钟的更改。然后，它会中断镜像并将数据存储库挂载到灾难恢复主机。此时，您可以根据预先规划的策略按任意顺序自动启动 VM 。


NOTE: 虽然ONTAP系统允许您将同一集群中的SVM配对以进行SnapMirror复制、但这种情况不会通过VLSR的测试和认证。因此、建议在使用VLSR时仅使用不同集群中的SVM。



== 采用 ONTAP 的 VLSR 以及其他使用情形：混合云和迁移

与本地存储选项相比，将 VLSR 部署与 ONTAP 高级数据管理功能相集成，可以显著提高扩展能力和性能。除此之外，它还带来了混合云的灵活性。通过混合云，您可以使用 FabricPool 将未使用的数据块从高性能阵列分层到首选超大规模存储器，从而节省资金。 StorageGRID 可以是 NetApp 等内部 S3 存储。此外，您还可以将SnapMirror用于具有软件定义的ONTAP Select或基于云的灾难恢复的基于边缘的系统，并使用Cloud Volumes ONTAP (CCVO) https://www.equinix.com/partners/netapp["基于Equix Metal®的NetApp存储"^]或，或其他托管的ONTAP服务。

借助FlexClone、您可以在云服务提供商的数据中心内执行测试故障转移、存储占用空间接近零。现在，保护您的组织的成本比以往任何时候都低。

VLSR 还可用于执行计划内迁移，方法是利用 SnapMirror 将 VM 从一个数据中心高效地传输到另一个数据中心，甚至在同一个数据中心内高效地传输 VM ，无论您自己还是通过任意数量的 NetApp 合作伙伴服务提供商。
