---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: 借助 ONTAP ， Storage Virtual Machine （ SVM ）的概念可在安全多租户环境中提供严格的分段。 
---
= 部署最佳实践
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
以下各节概述了ONTAP和VMware SRM的部署最佳实践。



== 使用最新版本的ONTAP工具10

与先前版本相比、ONTAP工具10提供了以下显著改进：

* 测试故障转移速度加快8倍*
* 清理和重新保护速度加快2倍*
* 故障转移速度加快32%*
* 扩展性更强
* 对共享站点布局的本机支持


*这些改进基于内部测试、可能因环境而异。



== SMT 的 SVM 布局和分段

借助 ONTAP ， Storage Virtual Machine （ SVM ）的概念可在安全多租户环境中提供严格的分段。一个 SVM 上的 SVM 用户无法从另一个 SVM 访问或管理资源。这样，您就可以利用 ONTAP 技术，为在同一集群上管理自己 SRM 工作流的不同业务单位创建单独的 SVM ，从而提高整体存储效率。

请考虑使用 SVM 范围的帐户和 SVM 管理 LIF 管理 ONTAP ，这样不仅可以改进安全控制，还可以提高性能。使用 SVM 范围的连接时，性能本身就会更高，因为处理整个集群中的所有资源（包括物理资源）并不需要 SRA 。相反，它只需要了解抽象到特定 SVM 的逻辑资产。



== 管理 ONTAP 9 系统的最佳实践

如前所述，您可以使用集群或 SVM 范围的凭据和管理 LIF 来管理 ONTAP 集群。为了获得最佳性能、您可能需要考虑在不使用Vvol的情况下使用SVM范围的凭据。但是，在执行此操作时，您应了解一些要求，并且确实会丢失某些功能。

* 默认 vsadmin SVM 帐户没有执行 ONTAP 工具任务所需的访问级别。因此、您需要创建新的SVM帐户。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["配置ONTAP用户角色和权限"]使用随附的JSON文件。这可以用于 SVM 或集群范围的帐户。
* 由于vCenter UI插件、VASA Provider和SRA服务器都是完全集成的微服务、因此您必须按照在适用于ONTAP的vCenter UI工具中添加存储的方式向SRM中的SRA适配器添加存储。否则， SRA 服务器可能无法识别通过 SRA 适配器从 SRM 发送的请求。
* 使用SVM范围的凭据时、不会执行NFS路径检查、除非首先 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["板载集群"]使用ONTAP工具管理器并将其与vCenter关联。这是因为物理位置从 SVM 中进行了逻辑抽象。不过，这并不是一个值得关注的发生原因，因为现代 ONTAP 系统在使用间接路径时不再出现任何明显的性能下降。
* 可能不会报告因存储效率而节省的聚合空间。
* 如果支持，则无法更新负载共享镜像。
* 可能不会在使用 SVM 范围的凭据管理的 ONTAP 系统上执行 EMS 日志记录。

