---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 由于适用于vSphere的ONTAP具有统一的SAN和NAS存储解决方案以及最新全SAN阵列中采用的全新简化离散式存储架构、客户信心十足地选择了该解决方案。此平台提供卓越的快照保护和强大的管理工具。通过将功能卸载到专用存储、ONTAP可以最大限度地利用主机资源、降低成本并保持最佳性能。此外、还可以使用Storage vMotion在VMFS、NFS或Vvol之间轻松迁移工作负载。 
---
= 为什么选择适用于VMware vSphere的ONTAP？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
客户可以放心地选择ONTAP for vSphere 作为 SAN 和 NAS 存储解决方案。最新的 All SAN 阵列采用了新的简化分解存储架构，为 SAN 存储管理员提供了熟悉的简化体验，同时保留了传统ONTAP系统的大部分集成和功能集。 ONTAP系统提供卓越的快照保护和强大的管理工具。通过将功能卸载到专用存储， ONTAP可以最大限度地利用主机资源、降低成本并保持最佳性能。此外，可以使用 Storage vMotion 轻松跨 VMFS、NFS 或vVols迁移工作负载。



== 使用适用于vSphere的ONTAP的优势

成千上万的客户选择ONTAP作为其vSphere存储解决方案的原因有很多、例如、支持SAN和NAS协议的统一存储系统、使用节省空间的快照的强大数据保护功能以及大量可帮助您管理应用程序数据的工具。使用与虚拟机管理程序不同的存储系统，您可以卸载许多功能，并最大程度地提高对 vSphere 主机系统的投资。这种方法不仅可以确保主机资源专注于应用程序工作负载，还可以避免存储操作对应用程序造成随机性能影响。

ONTAP与 vSphere 结合使用是一种很好的组合，可以让您减少主机硬件和 VMware 软件的费用。您还可以以较低的成本保护您的数据，同时保持始终如一的高性能。由于虚拟化工作负载是移动的，您可以探索使用 Storage vMotion 的不同方法在同一存储系统上跨 VMFS、NFS 或vVols数据存储移动虚拟机。

以下是当今客户重视的关键因素：

* *统一存储。*运行ONTAP 的系统在几个重要方面是统一的。最初，这种方法同时涉及 NAS 和 SAN 协议， ONTAP继续成为 SAN 的领先平台，同时又具有 NAS 方面的原有优势。在 vSphere 世界中，这种方法还意味着虚拟桌面基础架构 (VDI) 与虚拟服务器基础架构 (VSI) 的统一系统。运行ONTAP 的系统对于 VSI 而言通常比传统企业阵列更便宜，并且具有高级存储效率功能，可在同一系统中处理 VDI。 ONTAP还统一了各种存储介质，从 SSD 到 SATA，并且可以轻松将其扩展到云端。没有必要为了性能而购买一个存储操作系统，为了归档而购买另一个，为了云而购买另一个。  ONTAP将它们全部联系在一起。
* *全SAN阵列(ASA)。*最新的ONTAP ASA系统(从A1K、A90、A70、A50、A30和A20开始)基于新的存储架构构建、消除了管理聚合和卷的传统ONTAP存储模式。由于没有文件系统共享、因此不需要卷！连接到HA对的所有存储都被视为通用存储可用性区域(SAZ)、其中LUN和NVMe命名空间配置为"存储单元"(SUS)。最新的ASA系统易于管理、并具有SAN存储管理员熟悉的体验。这种新架构非常适合vSphere环境、因为它可以轻松管理存储资源、并为SAN存储管理员提供简化的体验。ASA架构还支持最新的基于网络结构的NVMe (NVMe-oF)技术、可为vSphere工作负载提供更高的性能和可扩展性。
* *快照技术。*ONTAP是第一家提供数据保护快照技术的公司、它仍然是业内最先进的公司。这种节省空间的数据保护方法已扩展为支持VMware vSphere APIS for Array Integration (VAAI)。通过这种集成、您可以利用ONTAP的快照功能执行备份和还原操作、从而减少对生产环境的影响。通过这种方法、您还可以使用快照快速恢复VM、从而减少恢复数据所需的时间和精力。此外、ONTAP的快照技术还与VMware的实时站点恢复(VSR、以前称为站点恢复管理器[SRM])解决方案相集成、为您的虚拟化环境提供全面的数据保护策略。
* *虚拟卷和基于存储策略的管理。* NetApp是 VMware 在 vSphere Virtual Volumes (vVols) 开发方面的早期设计合作伙伴，为vVols和 VMware vSphere APIs for Storage Awareness (VASA) 提供架构输入和早期支持。这种方法不仅为 VMFS 带来了细粒度的 VM 存储管理，还支持通过基于存储策略的管理实现存储配置的自动化。这种方法允许存储架构师设计具有不同功能的存储池，以便虚拟机管理员轻松使用。  ONTAP在 vVol 规模方面处于存储行业领先地位，在单个集群中支持数十万个vVols ，而企业阵列和小型闪存阵列供应商每个阵列仅支持几千个vVols 。  NetApp还通过即将推出的功能推动细粒度 VM 管理的发展。
* *存储效率。*尽管NetApp是第一个为生产工作负载提供重复数据删除功能的公司，但这项创新并不是该领域的第一次或最后一次创新。它从快照开始，这是一种节省空间且不会影响性能的数据保护机制，同时结合FlexClone技术，可以立即为生产和备份使用制作虚拟机的读/写副本。  NetApp继续提供内联功能，包括重复数据删除、压缩和零块重复数据删除，以从昂贵的 SSD 中榨取最多的存储空间。 ONTAP还增加了使用压缩将较小的 I/O 操作和文件打包到磁盘块中的功能。这些功能的结合使得客户普遍看到 VSI 节省高达 5:1，VDI 节省高达 30:1。最新一代ONTAP系统还包括硬件加速压缩和重复数据删除功能，可以进一步提高存储效率并降低成本。这种方法允许您在更少的空间内存储更多数据，从而降低总体存储成本并提高性能。  NetApp对其存储效率功能非常有信心，因此提供了一个链接： https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [效率保证^]。
* *多租户* ONTAP长期以来一直是多租户领域的领导者，允许您在单个集群上创建多个存储虚拟机 (SVM)。这种方法允许您隔离工作负载并为不同的租户提供不同级别的服务，使其成为服务提供商和大型企业的理想选择。最新一代ONTAP系统还包括对租户容量管理的支持。此功能允许您为每个租户设置容量限制，确保没有单个租户可以消耗所有可用资源。这种方法有助于确保所有租户都能获得他们期望的服务级别，同时还能在租户之间提供高级别的安全性和隔离。此外，ONTAP 的多租户功能与 VMware 的 vSphere 平台集成，使您可以通过以下方式轻松管理和监控虚拟化环境 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["适用于 VMware vSphere 的 ONTAP 工具"]和 https://docs.netapp.com/us-en/data-infrastructure-insights/["数据基础架构洞察力"]。
* *混合云。*无论用于本地私有云、公共云基础架构还是结合两者优点的混合云， ONTAP解决方案都可以帮助您构建数据结构以简化和优化数据管理。从高性能全闪存系统开始，然后将它们与磁盘或云存储系统结合，以实现数据保护和云计算。从 Azure、AWS、IBM 或 Google Cloud 中选择，以优化成本并避免锁定。根据需要利用对 OpenStack 和容器技术的高级支持。  NetApp还为ONTAP提供基于云的备份（ SnapMirror Cloud、 Cloud Backup Service和Cloud Sync）以及存储分层和归档工具（FabricPool ），以帮助降低运营费用并利用云的广泛覆盖范围。
* 等等。 * 利用 NetApp AFF A 系列阵列的极致性能，在管理成本的同时加快虚拟化基础架构的运行速度。使用横向扩展 ONTAP 集群享受从维护到升级到完全更换存储系统的无中断运行。利用 NetApp 加密功能保护空闲数据，无需额外付费。通过精细的服务质量功能确保性能满足业务服务级别要求。它们都是行业领先的企业级数据管理软件ONTAP提供的广泛功能的一部分。

