---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-fg.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: 本页介绍在 VMware vSphere 环境中实施 NetApp ONTAP Storage 解决方案的最佳实践。 
---
= FlexGroup 卷
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8增加了对vSphere中FlexGroup卷数据存储库的支持、并支持适用于VMware vSphere的ONTAP工具和适用于VMware vSphere的SnapCenter插件。FlexGroup 简化了大型数据存储库的创建，并自动创建了大量成分卷，以便从 ONTAP 系统中获得最大性能。如果您需要一个具有完整ONTAP集群功能的可扩展vSphere数据存储库、或者您的克隆工作负载非常庞大、可以从新的FlexGroup克隆机制中受益、请将FlexGroup与vSphere结合使用。

除了对 vSphere 工作负载进行大量系统测试之外， ONTAP 9.8 还为 FlexGroup 数据存储库添加了一种新的副本卸载机制。此操作会使用经过更新的复制引擎、该引擎会使用前几个克隆在每个成分卷中填充本地缓存。然后、可以使用此本地缓存根据需要快速例化VM克隆。

请考虑以下情形：

* 您已创建一个包含8个成分卷的新FlexGroup
* 新FlexGroup的缓存超时设置为160分钟


在这种情况下、要完成的前8个克隆将是完整副本、而不是本地文件克隆。在160秒超时时间到期之前对该VM执行任何其他克隆操作都将使用每个成分卷中的文件克隆引擎以循环方式创建几乎即时的副本、这些副本均匀分布在各个成分卷上。

卷收到的每个新克隆作业都会重置超时。如果示例FlexGroup中的成分卷在超时之前未收到克隆请求、则会清除该特定虚拟机的缓存、并且需要重新填充该卷。此外、如果原始克隆的源发生更改(例如、您已更新模板)、则每个成分卷上的本地缓存都将失效、以防止发生任何冲突。此缓存可进行调整、并可根据您的环境需求进行设置。

如果您无法充分利用FlexGroup缓存、但仍需要快速跨卷克隆、请考虑使用虚拟卷。与使用传统数据存储库相比、使用FlexVol进行跨卷克隆的速度要快得多、并且不依赖于缓存。

有关将FlexGroup与VAAI结合使用的详细信息、请参阅此知识库文章： https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F["VAAI：如何对FlexGroup卷使用缓存？"^]

ONTAP 9.8还为FlexGroup卷文件添加了新的基于文件的性能指标(IOPS、吞吐量和延迟)、您可以在适用于VMware vSphere的ONTAP工具信息板和VM报告中查看这些指标。适用于 VMware vSphere 的 ONTAP 工具插件还允许您结合使用最大和 / 或最小 IOPS 来设置服务质量（ QoS ）规则。可以在数据存储库中的所有 VM 之间设置这些值，也可以为特定 VM 单独设置这些值。

以下是 NetApp 开发的其他一些最佳实践：

* 使用FlexGroup卷配置默认值。虽然建议使用适用于 VMware vSphere 的 ONTAP 工具，因为它可以在 vSphere 中创建和挂载 FlexGroup ，但也可以使用 ONTAP System Manager 或命令行来满足特殊需求。即使如此、也应使用默认值、例如每个节点的成分卷成员数、因为这是在vSphere中经过最全面测试的内容。尽管如此、仍然完全支持非默认设置、例如更改成分卷的数量或放置。
* 在估算基于FlexGroup的数据存储库的规模时、请记住、FlexGroup由多个较小的FlexVol卷组成、这些卷会创建一个较大的命名空间。因此、如果使用包含八个成分卷的FlexGroup、请确保数据存储库大小至少是最大虚拟机大小的八倍。例如，如果您的环境中有一个 6 TB 的 VM ，请将 FlexGroup 数据存储库的大小调整为不小于 48 TB 。
* 允许 FlexGroup 管理数据存储库空间。已使用 vSphere 数据存储库测试自动调整大小和弹性调整。如果数据存储库容量接近全满，请使用适用于 VMware vSphere 的 ONTAP 工具或其他工具调整 FlexGroup 卷的大小。FlexGroup 可在成分卷之间保持容量和索引节点的平衡，并在容量允许的情况下优先将文件夹（ VM ）中的文件分配给同一成分卷。
* 从ONTAP 9.14.1开始、VMware和NetApp当前支持NFSv4.1会话中继。有关特定版本的详细信息、请参见NetApp NFS 4.1互操作性表说明。从vSphere 8.0U2开始、NFSv3不支持卷的多个物理路径、但支持nconnect。有关nconnect的详细信息、请参见 link:vmware-vsphere-network.html#nfs["此处"]。对于采用ONTAP 9.8的FlexGroup、我们建议的最佳实践是、让适用于VMware vSphere的ONTAP工具创建FlexGroup、但随后您应将其卸载、然后使用循环DNS重新挂载、以便在集群中分布负载。ONTAP工具在挂载数据存储库时仅使用一个LIF。重新挂载数据存储库后、可以使用ONTAP工具对其进行监控和管理。
* 在 9.8 版中，最多已对 1500 个 VM 的 FlexGroup vSphere 数据存储库支持进行了测试。
* 使用适用于 VMware VAAI 的 NFS 插件执行副本卸载。请注意、如前文所述、虽然FlexGroup数据存储库中的克隆功能得到了增强、但在FlexVol和/或FlexGroup卷之间复制VM时、ONTAP与ESXi主机副本相比、不会提供显著的性能优势。因此、在决定使用VAai或FlexGroup时、请考虑克隆工作负载。修改成分卷的数量是针对基于FlexGroup的克隆进行优化的一种方法。调整缓存超时。
* 使用适用于 VMware vSphere 9.8 的 ONTAP 工具使用 ONTAP 指标（信息板和 VM 报告）监控 FlexGroup VM 的性能，并管理各个 VM 上的 QoS 。目前无法通过 ONTAP 命令或 API 获得这些指标。
* 此时，可以在数据存储库中的各个 VM 或所有 VM 上设置 QoS （最大 / 最小 IOPS ）。在所有 VM 上设置 QoS 将取代任何单独的每 VM 设置。将来，设置不会扩展到新的或迁移的虚拟机；可以在新虚拟机上设置 QoS ，也可以将 QoS 重新应用于数据存储库中的所有虚拟机。如果虚拟机迁移到另一个数据存储库、则FlexGroup QoS策略也不会随虚拟机而变化。这一点与此不同、在迁移到其他数据存储库时、可以保留其QoS策略设置。
* 适用于VMware vSphere的SnapCenter插件4.4及更高版本支持备份和恢复主存储系统上FlexGroup数据存储库中的VM。4．6号选择控制阀为基于FlexGroup的数据存储库增加了SnapMirror支持。

