---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-sdrs.html 
keywords: Data protection, Space reclamation, VM and datastore cloning, Storage efficiency, thin provisioning, QoS, SIOC, Storage Distributed Resource Scheduler, DRS, Active IQ Unified Manager, Encryption 
summary: 使用 SnapCenter ，您可以创建可应用于多个作业的备份策略。这些策略可以定义计划，保留，复制和其他功能。它们仍然允许选择虚拟机一致的快照、从而利用虚拟机管理程序在创建VMware快照之前将I/O置于静修状态的功能。 
---
= VMware Storage Distributed Resource Scheduler
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Storage Distributed Resource Scheduler （ SDRS ）是一项 vSphere 功能，可根据当前 I/O 延迟和空间使用情况将 VM 放置在存储上。

然后，它会在数据存储库集群（也称为 Pod ）中的数据存储库之间无中断地移动虚拟机或 VMDK ，从而选择最佳数据存储库，以便将虚拟机或 VMDK 放置在数据存储库集群中。数据存储库集群是一组相似的数据存储库、从vSphere管理员的角度来看、这些数据存储库会聚合到一个使用单元中。

在将 SDRS 与适用于 VMware vSphere 的 NetApp ONTAP 工具结合使用时，您必须先使用此插件创建数据存储库，使用 vCenter 创建数据存储库集群，然后将此数据存储库添加到其中。创建数据存储库集群后，可以直接从详细信息页面上的配置向导将其他数据存储库添加到数据存储库集群中。

有关 SDRS 的其他 ONTAP 最佳实践包括：

* 集群中的所有数据存储库都应使用相同类型的存储（例如 SAS ， SATA 或 SSD ），可以是所有 VMFS 或 NFS 数据存储库，并且具有相同的复制和保护设置。
* 请考虑在默认（手动）模式下使用 SDRS 。通过此方法，您可以查看建议并决定是否应用这些建议。请注意 VMDK 迁移的以下影响：
+
** 在数据存储库之间移动 VMDK 时，通过 ONTAP 克隆或重复数据删除节省的任何空间都将丢失。您可以重新运行重复数据删除以重新获得这些节省。
** 在SDRS移动VMDK后、NetApp建议在源数据存储库中重新创建快照、因为空间会被移动的VM锁定。
** 在同一聚合上的数据存储库之间移动 VMDK 没有什么优势， SDRS 无法查看可能共享该聚合的其他工作负载。



