---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-flexgroups.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: 本页介绍在 VMware vSphere 环境中实施 NetApp ONTAP Storage 解决方案的最佳实践。 
---
= FlexGroup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.8 增加了对 vSphere 中 FlexGroup 数据存储库的支持，并增加了适用于 VMware vSphere 9.8 版本的 ONTAP 工具。

FlexGroup 简化了大型数据存储库的创建，并自动创建了大量成分卷，以便从 ONTAP 系统中获得最大性能。将 FlexGroup 与 vSphere 结合使用，可用于一个具有完整 ONTAP 集群功能的可扩展 vSphere 数据存储库。

除了对 vSphere 工作负载进行大量系统测试之外， ONTAP 9.8 还为 FlexGroup 数据存储库添加了一种新的副本卸载机制。这样可以使用经过改进的复制引擎在后台的成分卷之间复制文件，同时允许在源和目标上进行访问。如果需要，多个副本会根据规模在成分卷中使用可立即使用且节省空间的文件克隆。

ONTAP 9.8 还为 FlexGroup 文件添加了基于文件的新性能指标（ IOPS ，吞吐量和延迟），这些指标可在适用于 VMware vSphere 的 ONTAP 工具信息板和 VM 报告中查看。适用于 VMware vSphere 的 ONTAP 工具插件还允许您结合使用最大和 / 或最小 IOPS 来设置服务质量（ QoS ）规则。可以在数据存储库中的所有 VM 之间设置这些值，也可以为特定 VM 单独设置这些值。

以下是 NetApp 开发的其他一些最佳实践：

* 使用 FlexGroup 配置默认值。虽然建议使用适用于 VMware vSphere 的 ONTAP 工具，因为它可以在 vSphere 中创建和挂载 FlexGroup ，但也可以使用 ONTAP System Manager 或命令行来满足特殊需求。即使如此，也可以使用默认值，例如每个节点的成分卷成员数，因为这是已通过 vSphere 测试的结果。
* 在估算 FlexGroup 数据存储库的规模时，请记住， FlexGroup 由多个较小的 FlexVol 卷组成，这些卷会创建一个较大的命名空间。因此，请将数据存储库的大小至少设置为最大虚拟机的 8 倍。例如，如果您的环境中有一个 6 TB 的 VM ，请将 FlexGroup 数据存储库的大小调整为不小于 48 TB 。
* 允许 FlexGroup 管理数据存储库空间。已使用 vSphere 数据存储库测试自动调整大小和弹性调整。如果数据存储库容量接近全满，请使用适用于 VMware vSphere 的 ONTAP 工具或其他工具调整 FlexGroup 卷的大小。FlexGroup 可在成分卷之间保持容量和索引节点的平衡，并在容量允许的情况下优先将文件夹（ VM ）中的文件分配给同一成分卷。
* VMware 和 NetApp 目前不支持通用的多路径网络连接方法。对于 NFSv4.1 ， NetApp 支持 pNFS ，而 VMware 支持会话中继。NFSv3 不支持通过多个物理路径访问一个卷。对于采用 ONTAP 9.8 的 FlexGroup ，我们建议的最佳实践是让适用于 VMware vSphere 的 ONTAP 工具进行一次挂载，因为间接访问的影响通常很小（微秒）。可以使用循环DNS在FlexGroup中不同节点上的不同FlexGroup之间分布ESXi主机、但这需要在不使用适用于VMware vSphere的ONTAP工具的情况下创建和挂载ESXi主机。然后，性能管理功能将不可用。
* 在 9.8 版中，最多已对 1500 个 VM 的 FlexGroup vSphere 数据存储库支持进行了测试。
* 使用适用于 VMware VAAI 的 NFS 插件执行副本卸载。请注意，在 FlexGroup 数据存储库中增强了克隆功能，但在 FlexVol 和 / 或 FlexGroup 卷之间复制虚拟机时，与 ESXi 主机副本相比， ONTAP 不会提供显著的性能优势。
* 使用适用于 VMware vSphere 9.8 的 ONTAP 工具使用 ONTAP 指标（信息板和 VM 报告）监控 FlexGroup VM 的性能，并管理各个 VM 上的 QoS 。目前无法通过 ONTAP 命令或 API 获得这些指标。
* 此时，可以在数据存储库中的各个 VM 或所有 VM 上设置 QoS （最大 / 最小 IOPS ）。在所有 VM 上设置 QoS 将取代任何单独的每 VM 设置。将来，设置不会扩展到新的或迁移的虚拟机；可以在新虚拟机上设置 QoS ，也可以将 QoS 重新应用于数据存储库中的所有虚拟机。
* 适用于 VMware vSphere 的 SnapCenter 插件 4.4 版支持在主存储系统上的 FlexGroup 数据存储库中备份和恢复 VM 。虽然可以手动使用 SnapMirror 将 FlexGroup 复制到二级系统，但 4 号选择控制器不管理二级副本。

