---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: 此页面介绍了在VMware vSphere环境中实施ONTAP存储解决方案的最佳实践。 
---
= vSphere数据存储库和协议功能概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
可使用六种协议将VMware vSphere连接到运行ONTAP的系统上的数据存储库：

* FCP
* NVMe/FC
* NVMe/TCP
* iSCSI
* NFS v3
* NFS v4.1


FCP、NVMe/FC、NVMe/TCP和iSCSI是块协议、它们使用vSphere虚拟机文件系统(VMFS)将VM存储在ONTAP FlexVol volume中包含的ONTAP LUN或NVMe命名空间中。NFS 是一种文件协议，无需使用 VMFS 即可将虚拟机放置到数据存储库（即 ONTAP 卷）中。SMB (CIFS)、iSCSI、NVMe/TCP或NFS也可以从子操作系统直接使用到ONTAP。

以下表格展示了 vSphere 支持的使用 ONTAP 的传统数据存储功能。此信息不适用于 vVols 数据存储区，但它通常适用于使用支持的 ONTAP 版本的 vSphere 6.x 及更高版本。您也可以查阅 link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["VMware配置最大值工具"^] 有关特定 vSphere 版本的信息，以确认特定限制。

|===
| 功能 / 功能 | FC | iSCSI | NVMe-oF | NFS 


| 格式。 | VMFS 或原始设备映射（ RDM ） | VMFS 或 RDM | VMFS | 不适用 


| 数据存储库或 LUN 的最大数量 | 每个 ESXi 主机 1024 个 LUN，每个 LUN 最多 32 个路径，每个主机最多 4096 个总路径，每个数据存储区最多 128 个主机 | 每个 ESXi 主机 1024 个 LUN，每个 LUN 最多 32 个路径，每个主机最多 4096 个总路径，每个数据存储区最多 128 个主机 | 每个 ESXi 主机 256 个命名空间，每个主机每个命名空间最多 32 个路径，每个主机总共 2048 个路径，每个数据存储区最多 16 个主机 | 每个主机256个NFS连接(受nconnect和会话中继的影响)默认NFS。最大卷数为 8 。使用适用于 VMware vSphere 的 ONTAP 工具将其增加到 256 。 


| 最大数据存储库大小 | 64 TB | 64 TB | 64 TB | 使用 FlexGroup 卷时为 300 TB 或更高的 FlexVol 卷 


| 最大数据存储库文件大小 | 62 TB | 62 TB | 62 TB | 使用ONTAP 9.12.1P2及更高版本时为62 TB 


| 每个 LUN 或文件系统的最佳队列深度 | 64－256 | 64－256 | 已自动协商 | 请参见中的NFS.MaxQueueDepth link:vmware-vsphere-settings.html["建议的 ESXi 主机和其他 ONTAP 设置"^]。 
|===
下表列出了支持的 VMware 存储相关功能。

|===
| 容量 / 功能 | FC | iSCSI | NVMe-oF | NFS 


| VMotion | 是的。 | 是的。 | 是的。 | 是的。 


| 存储 vMotion | 是的。 | 是的。 | 是的。 | 是的。 


| VMware HA | 是的。 | 是的。 | 是的。 | 是的。 


| 存储分布式资源计划程序（ Storage Distributed Resource Scheduler ， SDRS ） | 是的。 | 是的。 | 是的。 | 是的。 


| 启用了VMware vStorage APIS for Data Protection (VADP)的备份软件 | 是的。 | 是的。 | 是的。 | 是的。 


| 虚拟机中的 Microsoft 集群服务（ MSCS ）或故障转移集群 | 是的。 | 是^1^ | 是^1^ | 不支持 


| 容错 | 是的。 | 是的。 | 是的。 | 是的。 


| Live Site Recon/Site Recovery Manager | 是的。 | 是的。 | 否^2^ | 仅v3 ^2^ 


| 精简配置的 VM （虚拟磁盘） | 是的。 | 是的。 | 是的。 | 是的。
如果不使用VAAI、则此设置是NFS上所有VM的默认设置。 


| VMware 原生多路径 | 是的。 | 是的。 | 是的。 | NFS v4.1会话中继需要ONTAP 9.14.1及更高版本 
|===
下表列出了支持的 ONTAP 存储管理功能。

|===
| 功能 / 功能 | FC | iSCSI | NVMe-oF | NFS 


| 重复数据删除 | 阵列中的节省量 | 阵列中的节省量 | 阵列中的节省量 | 数据存储库中的节省量 


| 精简配置 | 数据存储库或 RDM | 数据存储库或 RDM | 数据存储库 | 数据存储库 


| 调整数据存储库大小 | 仅增长 | 仅增长 | 仅增长 | 增长，自动增长和缩减 


| 适用于 Windows 和 Linux 应用程序的 SnapCenter 插件（在子系统中） | 是的。 | 是的。 | 是的。 | 是的。 


| 使用适用于 VMware vSphere 的 ONTAP 工具监控和主机配置 | 是的。 | 是的。 | 是的。 | 是的。 


| 使用适用于 VMware vSphere 的 ONTAP 工具进行配置 | 是的。 | 是的。 | 是的。 | 是的。 
|===
下表列出了支持的备份功能。

|===
| 功能 / 功能 | FC | iSCSI | NVMe-oF | NFS 


| ONTAP Snapshot | 是的。 | 是的。 | 是的。 | 是的。 


| 复制的备份支持 SRM | 是的。 | 是的。 | 否^2^ | 仅v3 ^2^ 


| 卷 SnapMirror | 是的。 | 是的。 | 是的。 | 是的。 


| VMDK 映像访问 | 支持SnapCenter和VADP的备份软件 | 支持SnapCenter和VADP的备份软件 | 支持SnapCenter和VADP的备份软件 | 启用了SnapCenter和VADP的备份软件、vSphere Client和vSphere Web Client数据存储库浏览器 


| vmdk 文件级访问 | 启用了SnapCenter和VADP的备份软件、仅限Windows | 启用了SnapCenter和VADP的备份软件、仅限Windows | 启用了SnapCenter和VADP的备份软件、仅限Windows | 支持SnapCenter和VADP的备份软件和第三方应用程序 


| NDMP 粒度 | 数据存储库 | 数据存储库 | 数据存储库 | 数据存储库或虚拟机 
|===
^1^ *NetApp 建议*对 Microsoft 群集使用来宾内 iSCSI，而不是在 VMFS 数据存储中使用启用了多写入器的 VMDK。这种方法得到了 Microsoft 和 VMware 的充分支持，通过 ONTAP 提供了极大的灵活性（SnapMirror 到本地或云中的 ONTAP 系统），易于配置和自动化，并且可以使用 SnapCenter 进行保护。vSphere 7 添加了新的群集 VMDK 选项。这与启用了多写入器的 VMDK 不同，后者需要启用了群集 VMDK 支持的 VMFS 6 数据存储。其他限制适用。有关配置指南，请参阅 VMware 的 link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Windows Server 故障转移集群设置"^] 文档。

^2^使用NVMe-oF和NFS v4.1的数据存储库需要vSphere复制。SRM目前不支持对NFS v4.1执行基于阵列的复制。适用于VMware vSphere Storage Replication Adapter (SRA)的ONTAP工具目前不支持使用NVMe-oF进行基于阵列的复制。



== 选择存储协议

运行 ONTAP 的系统支持所有主要的存储协议，因此客户可以根据现有和计划的网络基础设施和员工技能选择最适合其环境的存储协议。从历史上看，NetApp 测试通常显示以相似线速和连接数量运行的协议之间几乎没有差异。但是，NVMe-oF（NVMe/TCP 和 NVMe/FC）在 IOPS 方面显示出显著的增益，延迟减少，并且存储 IO 的主机 CPU 消耗减少了 50% 或更多。另一方面，NFS 提供了最大的灵活性和易管理性，特别是对于大量的虚拟机。所有这些协议都可以使用 ONTAP tools for VMware vSphere 进行使用和管理，该工具提供了一个简单的界面来创建和管理数据存储。

在考虑选择协议时，以下因素可能会很有用：

* *当前操作环境。*虽然IT团队通常擅长管理以太网IP基础架构、但并非所有IT团队都擅长管理FC SAN网络结构。但是、如果使用的是不针对存储流量设计的通用IP网络、则可能效果不会很好。请考虑您已有的网络基础架构，任何计划内的改进，以及管理这些改进的人员的技能和可用性。
* * 易于设置。 * 除了 FC 网络结构的初始配置（额外的交换机以及 HBA 和固件的布线，分区以及互操作性验证）之外，块协议还需要创建和映射 LUN 以及通过子操作系统进行发现和格式化。创建并导出 NFS 卷后，它们将由 ESXi 主机挂载并准备好使用。NFS 没有特殊的硬件资格认定或固件可供管理。
* *易于管理。*对于 SAN 协议，如果需要更多空间，则需要执行几个步骤，包括扩展 LUN、重新扫描以发现新的大小，然后扩展文件系统。虽然可以增加 LUN，但减小 LUN 的大小则不可能。NFS 允许轻松调整大小，并且可以由存储系统自动调整大小。SAN 通过来宾操作系统 DEALLOCATE/TRIM/UNMAP 命令提供空间回收，允许将已删除文件的空间返回到阵列。这种类型的空间回收对于 NFS 数据存储区是不可能的。
* * 存储空间透明度。 * 在 NFS 环境中，存储利用率通常更容易查看，因为精简配置可以立即实现节省。同样，重复数据删除和克隆节省的空间可立即用于同一数据存储库中的其他虚拟机或其他存储系统卷。NFS 数据存储库中的虚拟机密度通常也会更高，这样可以减少要管理的数据存储库数量，从而节省重复数据删除的空间，并降低管理成本。




== 数据存储库布局

ONTAP 存储系统可以非常灵活地为 VM 和虚拟磁盘创建数据存储库。虽然在使用ONTAP工具为vSphere配置数据存储库时会应用许多ONTAP最佳实践(在一节中列出link:vmware-vsphere-settings.html["建议的 ESXi 主机和其他 ONTAP 设置"])，但还需要考虑以下一些准则：

* 使用 ONTAP NFS 数据存储部署 vSphere 可实现高性能、易于管理的实施，提供基于块的存储协议无法获得的 VM 与数据存储比率。这种架构可以使数据存储密度增加十倍，并相应地减少数据存储的数量。虽然较大的数据存储可以提高存储效率并提供运营优势，但请考虑每个节点至少使用四个数据存储（FlexVol 卷）将 VM 存储在单个 ONTAP 控制器上，以从硬件资源中获得最大性能。这种方法还允许您建立具有不同恢复策略的数据存储。根据业务需求，某些数据存储可以比其他数据存储更频繁地备份或复制。对于性能而言，FlexGroup 卷不需要多个数据存储，因为它们通过设计进行扩展。
* *NetApp 建议*对大多数 NFS 数据存储使用 FlexVol 卷。从 ONTAP 9.8 开始，FlexGroup 卷也支持用作数据存储，通常建议用于某些用例。一般不建议使用其他 ONTAP 存储容器，例如 qtree，因为目前 ONTAP tools for VMware vSphere 或 NetApp SnapCenter plugin for VMware vSphere 都不支持这些容器。
* 对于 FlexVol 卷数据存储库，大小合适的数据存储库大约为 4 TB 到 8 TB 。这种大小可以很好地平衡性能，易管理性和数据保护。从小规模入手（例如 4 TB ），然后根据需要扩展数据存储库（最大 300 TB ）。较小的数据存储库可以更快地从备份中或发生灾难后进行恢复，并可在集群中快速移动。请考虑使用 ONTAP 自动调整大小功能在已用空间发生变化时自动增长和缩减卷。默认情况下、适用于VMware vSphere的ONTAP工具数据存储库配置向导会对新数据存储库使用自动调整大小。可以使用 System Manager 或命令行对增长和缩减阈值以及大小上限和下限进行其他自定义。
* 或者、也可以为VMFS数据存储库配置可通过FC、iSCSI、NVMe/FC或NVMe/TCP访问的LUN或NVMe命名空间(在新ASA系统中称为存储单元)。VMFS允许集群中的每个ESX服务器同时访问数据存储库。VMFS 数据存储库的大小最多可达 64 TB ，并且最多可包含 32 个 2 TB LUN （ VMFS 3 ）或一个 64 TB LUN （ VMFS 5 ）。在AFF、ASA和FAS系统上、ONTAP的最大LUN大小为128 TB。NetApp始终建议对每个数据存储库使用一个大型LUN、而不是尝试使用块区。与NFS一样、请考虑使用多个数据存储库(卷或存储单元)、以最大程度地提高单个ONTAP控制器的性能。
* 较旧的子操作系统（ OS ）需要与存储系统对齐，以获得最佳性能和存储效率。但是， Microsoft 和 Linux 分销商（例如 Red Hat ）提供的现代供应商支持的操作系统不再需要进行调整，以便在虚拟环境中将文件系统分区与底层存储系统的块对齐。如果您使用的是可能需要对齐的旧操作系统、请使用"VM对齐"搜索NetApp支持知识库文章、或者向NetApp销售人员或合作伙伴联系人申请TR-3747副本。
* 避免在子操作系统中使用碎片整理实用程序、因为这不会带来任何性能优势、并会影响存储效率和快照空间使用量。此外，还应考虑在子操作系统中关闭虚拟桌面的搜索索引。
* ONTAP 凭借创新的存储效率功能引领行业发展，帮助您充分利用可用磁盘空间。AFF 系统通过默认实时重复数据删除和数据压缩进一步提高了这种效率。数据会在聚合中的所有卷之间进行重复数据删除，因此您无需再将相似的操作系统和类似应用程序分组到一个数据存储库中，即可最大程度地节省空间。
* 在某些情况下，您甚至可能不需要数据存储库。考虑子系统拥有的文件系统、例如由子系统管理的NFS、SMB、NVMe/TCP或iSCSI文件系统。有关具体的应用指南，请参见适用于您的应用程序的 NetApp 技术报告。例如、link:../oracle/oracle-overview.html["基于 ONTAP 的 Oracle 数据库"]中有一节介绍虚拟化、并提供了有用的详细信息。
* 一级磁盘（或经过改进的虚拟磁盘）支持独立于运行 vSphere 6.5 及更高版本的 VM 的 vCenter 管理磁盘。虽然它们主要由 API 管理，但对于 VVOL 很有用，尤其是在由 OpenStack 或 Kubernetes 工具管理时。ONTAP 以及适用于 VMware vSphere 的 ONTAP 工具均支持这些功能。




== 数据存储库和 VM 迁移

将 VM 从另一个存储系统上的现有数据存储库迁移到 ONTAP 时，请记住以下一些实践：

* 使用 Storage vMotion 将虚拟机的批量移动到 ONTAP 。这种方法不仅不会对正在运行的 VM 造成中断，而且还可以通过实时重复数据删除和数据压缩等 ONTAP 存储效率功能在数据迁移时对其进行处理。请考虑使用 vCenter 功能从清单列表中选择多个 VM ，然后在适当的时间计划迁移（单击操作时使用 Ctrl 键）。
* 虽然您可以仔细规划迁移到适当的目标数据存储，但批量迁移后再根据需要进行组织通常更简单。如果您有特定的数据保护需求，例如不同的 Snapshot 计划，您可能需要使用此方法来指导您迁移到不同的数据存储。此外，一旦 VM 在 NetApp 集群上，存储 vMotion 可以使用 VAAI 卸载在集群上的数据存储之间移动 VM，而无需基于主机的副本。请注意，NFS 不会卸载已开机 VM 的存储 vMotion；但是，VMFS 会。
* 需要更仔细迁移的虚拟机包括使用连接存储的数据库和应用程序。一般情况下、请考虑使用应用程序的工具来管理迁移。对于 Oracle ，请考虑使用 RMAN 或 ASM 等 Oracle 工具迁移数据库文件。有关详细信息、请参见 https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["将Oracle数据库迁移到ONTAP存储系统"^] 。同样，对于 SQL Server ，请考虑使用 SQL Server Management Studio 或 NetApp 工具，例如适用于 SQL Server 的 SnapManager 或 SnapCenter 。




== 适用于 VMware vSphere 的 ONTAP 工具

在使用运行 ONTAP 的系统与 vSphere 时，最重要的最佳实践是安装并使用 ONTAP tools for VMware vSphere 插件（以前称为 Virtual Storage Console）。这个 vCenter 插件简化了存储管理，提高了可用性，并降低了存储成本和运维开销，无论是在 ASA、AFF、FAS 还是 ONTAP Select（在 VMware 或 KVM 虚拟机中运行的 ONTAP 软件定义版本）上使用 SAN 或 NAS。它采用了为数据存储配置制定的最佳实践，并针对多路径和 HBA 超时优化了 ESXi 主机设置（这些内容在附录 B 中有描述）。由于它是一个 vCenter 插件，所有连接到 vCenter 服务器的 vSphere Web 客户端都可以使用它。

此插件还可帮助您在 vSphere 环境中使用其他 ONTAP 工具。您可以通过此插件安装适用于VMware VAAI的NFS插件、以便将副本卸载到ONTAP以执行VM克隆操作、为厚虚拟磁盘文件预留空间以及卸载ONTAP快照。


NOTE: 在基于映像的 vSphere 群集上，仍要将 NFS 插件添加到映像中，以便在使用 ONTAP tools 安装时不会出现合规性问题。

ONTAP工具也是适用于ONTAP的VASA Provider的许多功能的管理界面、支持使用VVO尔 进行基于存储策略的管理。

一般来说、* NetApp建议*在vCenter中使用适用于VMware vSphere的ONTAP工具界面来配置传统数据存储库和Vvol数据存储库、以确保遵循最佳实践。



== 常规网络连接

在运行 ONTAP 的系统中使用 vSphere 时配置网络设置非常简单，与其他网络配置类似。以下是一些需要考虑的事项：

* 将存储网络流量与其他网络分开。可以通过使用专用 VLAN 或单独的存储交换机来实现单独的网络。如果存储网络共享上行链路等物理路径，您可能需要 QoS 或其他上行链路端口来确保带宽充足。请勿将主机直接连接到存储；使用交换机提供冗余路径、并允许VMware HA在没有干预的情况下运行。请参见 link:vmware-vsphere-network.html["直连网络"] 适用于追加信息 。
* 如果您的网络需要并支持巨型帧，则可以使用巨型帧，尤其是在使用 iSCSI 时。如果使用这些协议，请确保在存储和 ESXi 主机之间的路径中的所有网络设备， VLAN 等上对其进行相同的配置。否则，您可能会看到性能或连接问题。此外，还必须在 ESXi 虚拟交换机， VMkernel 端口以及每个 ONTAP 节点的物理端口或接口组上以相同的方式设置 MTU 。
* NetApp仅建议在ONTAP集群中的集群互连端口上禁用网络流量控制。对于用于数据流量的其余网络端口， NetApp 不提供其他最佳实践建议。您应根据需要启用或禁用。有关流量控制的更多背景信息、请参见 https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^]。
* 当ESXi和ONTAP存储阵列连接到以太网存储网络时，*PortFast* NetApp建议将这些系统连接到的以太网端口配置为快速生成树协议(RSTP)边缘端口或使用Cisco端口快速功能。* NetApp建议*在使用Cisco PortFast功能且为ESXi服务器或ONTAP存储阵列启用了802.1Q VLAN中继的环境中启用生成树PortFast中继功能。
* * NetApp建议*以下链路聚合最佳实践：
+
** 使用支持使用多机箱链路聚合组方法（例如 Cisco 的 Virtual PortChannel (vPC)）在两个独立交换机机箱上进行端口链路聚合的交换机。
** 对连接到ESXi的交换机端口禁用LACP、除非您使用的是配置了LACP的dvSwitches 5.1或更高版本。
** 使用LACP为具有端口或IP哈希动态多模式接口组的ONTAP存储系统创建链路聚合。请参见 https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["网络管理"^] 以获得进一步指导。
** 如果对vSphere分布式交换机使用静态链路聚合(例如EtherChannel)和标准vswitch或基于LACP的链路聚合、请在ESXi上使用IP哈希绑定策略。如果未使用链路聚合、请改用"基于源虚拟端口ID路由"。



