---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-settings.html 
keywords: VMware,vSphere,ESXi,settings,NFS,iSCSI,FC,FCP 
summary: 本文档对建议的存储和网络设置进行了分类和列举。 
---
= 建议的 ESXi 主机和其他 ONTAP 设置
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp为NFS和块协议开发了一组最佳ESXi主机设置。此外、还提供了有关多路径和HBA超时设置的特定指导、以便根据NetApp和VMware内部测试在ONTAP中正常运行。

可以使用适用于VMware vSphere的ONTAP工具轻松设置这些值：从摘要信息板中、单击主机系统portlet中的编辑设置、或者在vCenter中右键单击主机、然后导航到ONTAP工具>设置建议值。

下面是当前所有受支持的ONTAP版本的建议主机设置。

|===


| *主机设置* | * NetApp建议值* | *需要重新启动* 


3+| * ESXi高级配置* 


| VMFS3.HardwareAcceleratedLocking | 保留默认值(1) | 否 


| VMFS3.EnableBlockDelete | 保留默认值(0)、但可以根据需要进行更改。有关详细信息、请参见 link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-provisioning-and-space-reclamation-in-vsphere/storage-space-reclamation-in-vsphere/space-reclamation-for-guest-operating-systems.html["VMFS5虚拟机的空间回收"] | 否 


| VMFS3.EnableVMFS6Unmap | 保留默认值(1)
有关详细信息，请参见 link:https://core.vmware.com/resource/vmware-vsphere-apis-array-integration-vaai#sec9426-sub4["VMware vSphere API：阵列集成(VAAI)"] | 否 


3+| *NFS设置* 


| Net.TcpipHeapSize | vSphere 6.0 或更高版本，设置为 32 。
所有其他NFS配置、设置为30 | 是的。 


| Net.TcpipHeapMax | 对于大多数vSphere 6.X版本、设置为512 MB。
对于6.5U3、6.7U3和7.0或更高版本、设置为默认值(1024MB)。 | 是的。 


| NFS.MaxVolumes | vSphere 6.0或更高版本、请设置为256
所有其他NFS配置均设置为64。 | 否 


| NFS41.MaxVolumes | vSphere 6.0或更高版本、请设置为256。 | 否 


| NFS.MaxQueueDepth^1^ | vSphere 6.0或更高版本、设置为128 | 是的。 


| nfs.HeartbeatMaxFailures | 对于所有NFS配置、均设置为10 | 否 


| nfs.Heartbeat频率 | 对于所有NFS配置、请设置为12 | 否 


| nfs.HeartbeatTimeout | 对于所有NFS配置、设置为5。 | 否 


| SUNRPC.MaxConnPerIP | vSphere 7.0或更高版本、请设置为128。 | 否 


3+| * FC/FCoE 设置 * 


| 路径选择策略 | 如果使用采用 ALUA 的 FC 路径，则设置为 RR （轮循）。对于所有其他配置，设置为 FIXED 。
将此值设置为 RR 有助于在所有主动 / 优化路径之间实现负载平衡。
固定值适用于较旧的非 ALUA 配置，有助于防止代理 I/O换言之、它有助于防止I/O流向在7-模式下运行Data ONTAP 的环境中高可用性(HA)对的另一节点 | 否 


| disk.qFullSampSize | 对于所有配置，均设置为 32 。
设置此值有助于防止出现 I/O 错误。 | 否 


| disk.qFullThreshold | 对于所有配置、均设置为8。
设置此值有助于防止出现 I/O 错误。 | 否 


| Emulex FC HBA 超时 | 使用默认值。 | 否 


| QLogic FC HBA 超时 | 使用默认值。 | 否 


3+| * iSCSI 设置 * 


| 路径选择策略 | 对于所有 iSCSI 路径，设置为 RR （轮循）。
将此值设置为 RR 有助于在所有主动 / 优化路径之间实现负载平衡。 | 否 


| disk.qFullSampSize | 对于所有配置，均设置为 32 。
设置此值有助于防止出现I/O错误 | 否 


| disk.qFullThreshold | 对于所有配置、均设置为8。
设置此值有助于防止出现 I/O 错误。 | 否 
|===

NOTE: 1—使用VMware vSphere ESXi 7.0.1和VMware vSphere ESXi 7.0.2时、NFS高级配置选项MaxQueueDepth可能无法按预期工作。请参考 link:https://kb.vmware.com/s/article/86331?lang=en_US["VMware知识库86331"] 有关详细信息 ...

在创建 ONTAP FlexVol 卷和 LUN 时， ONTAP 工具还会指定某些默认设置：

|===


| * ONTAP Tool* | *默认设置* 


| Snapshot 预留（ -percent-snapshot-space ） | 0 


| 预留百分比（ -fractional-reserve ） | 0 


| 访问时间更新（ -atime-update ） | false 


| 最小预读（ -min-readahead ） | false 


| 计划快照 | 无 


| 存储效率 | enabled 


| 卷保证 | 无（精简配置） 


| 卷自动调整大小 | grow_shrink 


| LUN 空间预留 | 已禁用 


| LUN 空间分配 | enabled 
|===


== 多路径性能设置

虽然当前未使用可用的ONTAP工具进行配置、但NetApp建议使用以下配置选项：

* 在高性能环境中或使用单个 LUN 数据存储库测试性能时，请考虑将轮循（ VMW_PSP_RR ）路径选择策略（ PSP ）的负载平衡设置从默认 IOPS 设置 1000 更改为 1 。有关详细信息、请参见link:https://knowledge.broadcom.com/external/article?legacyId=2069356["VMware 知识库 2069356"^]。
* 在 vSphere 6.7 Update 1 中， VMware 为轮循 PSP 引入了一种新的延迟负载平衡机制。新选项会在选择最佳 I/O 路径时考虑 I/O 带宽和路径延迟在路径连接不等的环境中使用它可能会受益、例如、一条路径上的网络跃点比另一条路径多、或者使用NetApp全SAN阵列(ASA)系统。有关详细信息、请参见 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts.html#GUID-1940AE9E-04CF-40BE-BB71-398621F0642E-en["更改延迟轮循的默认参数"^] 。




== 其他文档

对于采用vSphere 7的FCP和iSCSI、有关详细信息、请参见。link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["将VMware vSphere 7.x与ONTAP结合使用"^]对于采用vSphere 8的FCP和iSCSI、有关详细信息、请参见link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["将VMware vSphere 8.x与ONTAP结合使用"^]。对于采用vSphere 7的NVMe-oF、有关详细信息、请参见link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["对于NVMe-oF、有关详细信息、请参见适用于采用ONTAP的ESXi 7.x的NVMe-oF主机配置"^]。对于采用vSphere 8的NVMe-oF、有关详细信息、请参见link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["对于NVMe-oF、有关详细信息、请参见适用于采用ONTAP的ESXi 8.x的NVMe-oF主机配置"^]
