---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 由于适用于vSphere的ONTAP具有统一的SAN和NAS存储解决方案以及最新全SAN阵列中采用的全新简化离散式存储架构、客户信心十足地选择了该解决方案。此平台提供卓越的快照保护和强大的管理工具。通过将功能卸载到专用存储、ONTAP可以最大限度地利用主机资源、降低成本并保持最佳性能。此外、还可以使用Storage vMotion在VMFS、NFS或Vvol之间轻松迁移工作负载。 
---
= 为什么选择适用于VMware vSphere的ONTAP？
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
客户信心十足地选择适用于vSphere的ONTAP作为SAN和NAS存储解决方案。最新的全SAN阵列采用了经过简化的全新离散式存储架构、可提供SAN存储管理员熟悉的简化体验、同时保留传统ONTAP系统的大部分集成和功能集。ONTAP系统提供卓越的快照保护和强大的管理工具。通过将功能卸载到专用存储、ONTAP可以最大限度地利用主机资源、降低成本并保持最佳性能。此外、还可以使用Storage vMotion在VMFS、NFS或Vvol之间轻松迁移工作负载。



== 使用适用于vSphere的ONTAP的优势

成千上万的客户选择ONTAP作为其vSphere存储解决方案的原因有很多、例如、支持SAN和NAS协议的统一存储系统、使用节省空间的快照的强大数据保护功能以及大量可帮助您管理应用程序数据的工具。使用与虚拟机管理程序不同的存储系统，您可以卸载许多功能，并最大程度地提高对 vSphere 主机系统的投资。这种方法不仅可以确保主机资源专注于应用程序工作负载，还可以避免存储操作对应用程序造成随机性能影响。

将 ONTAP 与 vSphere 结合使用是一个很好的组合，可帮助您降低主机硬件和 VMware 软件支出。您还可以通过稳定一致的高性能以更低的成本保护数据。由于虚拟化工作负载是移动的，因此您可以使用 Storage vMotion 探索不同的方法，以便在 VMFS ， NFS 或 VVOL 数据存储库之间移动 VM ，所有这些都位于同一存储系统上。

以下是客户目前重视的关键因素：

* *统一存储*运行ONTAP的系统在多个重要方面实现了统一。最初，这种方法既指 NAS 协议，也指 SAN 协议，而 ONTAP 除了在 NAS 中具有最初的优势之外，仍然是 SAN 的领先平台。在 vSphere 环境中，这种方法还可能意味着为虚拟桌面基础架构 (VDI) 和虚拟服务器基础架构（ VSI ）提供一个统一的系统。与传统企业阵列相比、运行ONTAP的系统在VSI方面的成本通常较低、但具有高级存储效率功能、可以在同一系统中处理VDI。ONTAP 还统一了从 SSD 到 SATA 的各种存储介质，并可轻松地将其扩展到云。无需购买一个存储操作系统来提高性能、一个用于归档、另一个用于云。ONTAP 将所有这些问题联系在一起。
* *全SAN阵列(ASA)。*最新的ONTAP ASA系统(从A1K、A90、A70、A50、A30和A20开始)基于新的存储架构构建、消除了管理聚合和卷的传统ONTAP存储模式。由于没有文件系统共享、因此不需要卷！连接到HA对的所有存储都被视为通用存储可用性区域(SAZ)、其中LUN和NVMe命名空间配置为"存储单元"(SUS)。最新的ASA系统易于管理、并具有SAN存储管理员熟悉的体验。这种新架构非常适合vSphere环境、因为它可以轻松管理存储资源、并为SAN存储管理员提供简化的体验。ASA架构还支持最新的基于网络结构的NVMe (NVMe-oF)技术、可为vSphere工作负载提供更高的性能和可扩展性。
* *快照技术。*ONTAP是第一家提供数据保护快照技术的公司、它仍然是业内最先进的公司。这种节省空间的数据保护方法已扩展为支持VMware vSphere APIS for Array Integration (VAAI)。通过这种集成、您可以利用ONTAP的快照功能执行备份和还原操作、从而减少对生产环境的影响。通过这种方法、您还可以使用快照快速恢复VM、从而减少恢复数据所需的时间和精力。此外、ONTAP的快照技术还与VMware的实时站点恢复(VSR、以前称为站点恢复管理器[SRM])解决方案相集成、为您的虚拟化环境提供全面的数据保护策略。
* *基于虚拟卷和存储策略的管理。*NetApp 是 VMware 在开发 vSphere 虚拟卷（ VVOL ）方面的早期设计合作伙伴，为 VVOL 和 VMware vSphere 存储感知 API （ VASA ）提供架构输入和早期支持。这种方法不仅可以为VMFS提供精细的VM存储管理、还可以通过基于存储策略的管理来实现存储配置自动化。通过这种方法，存储架构师可以设计具有不同功能的存储池， VM 管理员可以轻松地使用这些功能。ONTAP 在 VVOL 规模方面处于存储行业的领先地位，在一个集群中支持数十万个 VVOL ，而企业级阵列和小型闪存阵列供应商则支持每个阵列仅支持数千个 VVOL 。NetApp还在利用即将推出的功能推动精细VM管理的发展。
* *存储效率*虽然NetApp是第一家为生产工作负载提供重复数据删除的公司、但这项创新并不是该领域的第一项或最后一项创新。它从快照开始、这是一种节省空间的数据保护机制、不会影响性能、同时还采用了FlexClone技术、可即时为VM创建读/写副本、以供生产和备份使用。NetApp 继续提供包括重复数据删除，数据压缩和零块重复数据删除在内的实时功能，以从昂贵的 SSD 中挤出最大的存储空间。此外、ONTAP还增加了通过数据缩减将较小的I/O操作和文件打包到磁盘块中的功能。这些功能的结合使客户通常可以看到、VSI和VDI的节省比率分别高达5：1和30：1。最新一代ONTAP系统还包括硬件加速数据压缩和重复数据删除、可进一步提高存储效率并降低成本。通过这种方法、您可以在更少的空间中存储更多数据、从而降低整体存储成本并提高性能。NetApp对其存储效率功能充满信心、因此提供了一个链接：https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [效率担保^]。
* *多租户。*长期以来、ONTAP一直是多租户领域的领导者、支持您在一个集群上创建多个Storage Virtual Machine (SVM)。通过这种方法、您可以隔离工作负载并为不同租户提供不同级别的服务、使其成为服务提供商和大型企业的理想选择。最新一代的ONTAP系统还包括支持期限容量管理。通过此功能、您可以为每个租户设置容量限制、以确保任何一个租户都无法使用所有可用资源。这种方法有助于确保所有租户都能获得预期的服务级别、同时还能在租户之间提供高级别的安全性和隔离。此外，ONTAP的多租户功能与VMware的vSphere平台相集成，使您可以通过和轻松管理和 https://docs.netapp.com/us-en/data-infrastructure-insights/["数据基础架构洞察力"]监控虚拟化环境 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["适用于 VMware vSphere 的 ONTAP 工具"]。
* * 混合云。 * 无论是用于内部私有云，公有云基础架构还是结合两者优势的混合云， ONTAP 解决方案均可帮助您构建数据网络结构，以简化和优化数据管理。从高性能全闪存系统开始，然后将其与磁盘或云存储系统结合使用，以实现数据保护和云计算。您可以选择 Azure ， AWS ， IBM 或 Google 云来优化成本并避免受制于云。根据需要利用对 OpenStack 和容器技术的高级支持。NetApp 还为 ONTAP 提供基于云的备份（ SnapMirror 云， Cloud Backup Service 和 Cloud Sync ）以及存储分层和归档工具（ FabricPool ），以帮助降低运营支出并利用云的广泛覆盖范围。
* 等等。 * 利用 NetApp AFF A 系列阵列的极致性能，在管理成本的同时加快虚拟化基础架构的运行速度。使用横向扩展 ONTAP 集群享受从维护到升级到完全更换存储系统的无中断运行。利用 NetApp 加密功能保护空闲数据，无需额外付费。通过精细的服务质量功能确保性能满足业务服务级别要求。它们都是行业领先的企业级数据管理软件ONTAP提供的广泛功能的一部分。

