---
sidebar: sidebar 
permalink: epic/epic-overview.html 
keywords: epic,cache,iris 
summary: ONTAP上的EPIC概述 
---
= ONTAP上的经典
:allow-uri-read: 


[role="lead"]
数字化转型的关键在于利用数据实现更多优势。


NOTE: 本文档将取代先前发布的技术报告_TR-3923：《适用于Epic_的NetApp最佳实践》。

医院需要大量数据才能开启数字化转型之旅。在治疗患者、管理员工计划和医疗资源的过程中、一部分是收集和处理信息。但是、许多操作仍然是手动执行的或通过过时的系统执行的。其中一个常数是数据量持续呈指数级增长、因此越来越难以管理。

这一问题的主要原因是医院数据往往存储在数据孤岛中。手动输入和更新所花费的时间过长、从而导致作业中断和错误。本文档是医疗保健数据Epic电子健康记录(EHR)的一部分。但是、此处介绍的数据管理策略可以而且应该应用于所有医疗保健数据。NetApp在打造现代化和简化数字基础架构方面拥有骄人的历史。我们的智能数据基础架构是数字化转型的基础。

NetApp提供一个单一的数据管理解决方案来满足所有医疗保健需求、我们能够指导医院完成数字化转型之旅。通过构建结构化和智能解决方案、医疗保健行业可以充分发挥这些宝贵信息的价值。这一框架可帮助医疗提供者更快地诊断疾病，并制定个性化治疗计划，以更好地支持紧急情况下的决策过程。您还将能够构建自己的智能数据基础架构、使医院能够打破数据孤岛、促进数据互操作性并保护敏感的患者信息。

使用本文档作为成功构建和实施Epic EHR的指南。无需构建多个Epic孤岛、只需构建一个Epic数据基础架构、即可实现医院转型。



== 目的

本文档介绍了将NetApp存储集成到Epic软件环境中的最佳实践。它包含以下部分：

* 从技术上了解Epic软件环境及其在各种配置中的存储要求。
* Epic存储注意事项、介绍Epic解决方案的重要决策因素。
* NetApp存储建议、介绍满足Epic存储要求的NetApp存储配置最佳实践。




== 范围

本文档不涵盖以下主题：

* 中介绍了定量性能要求和规模估算指导 https://fieldportal.netapp.com/content/192412?assetComponentId=192510["TR-3930i ：《 NetApp Epic 规模估算准则》"^](需要NetApp登录)




== 受众

NetApp假定读者具备以下背景知识：

* 深入了解SAN和NAS概念
* 熟悉ONTAP存储系统的技术知识
* 熟悉ONTAP的配置和管理

