---
sidebar: sidebar 
permalink: mysql/mysql-overview.html 
keywords: MySQL,MariaDB,TR-4722 
summary: 基于ONTAP的MySQL 
---
= 基于ONTAP的MySQL数据库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL及其变体(包括MariaDB和Percona MySQL)是世界上最受欢迎的数据库。


NOTE: 此ONTAP和MySQL数据库文档将取代先前发布的_TR-4722：《基于NetApp ONTAP的MySQL数据库最佳实践》。_

MySQL的功能包括：

* *降低TCO。* MySQL是一款功能强大的免费开源数据库管理系统、已上市多年。它非常稳定。它具有社区支持、可帮助维护、调试和添加新功能。如果Web应用程序需要多个数据库、或者需要负载平衡或共享、您可以轻松设置数据库实例、而无需为每个实例设置一个许可证。
* *可靠性、性能和易用性。* MySQL的一个特点是卓越的性能和可扩展性，这就是为什么许多基于Web的企业都使用它。MySQL利用多项关键优势来提供快速性能。因为只需单击鼠标(或触摸屏幕)、就可以快速响应客户的询问和活动、这一点至关重要。为基于Web的应用程序提供服务的数据库需要为读取(简单查询和复杂查询)和写入操作提供极致性能。
* *数据库开发、设计和管理。* MySQL Workbench提供集成的开发、设计和管理环境，可提高开发人员和数据库管理员的工作效率。不同的开发人员在数据库中寻找不同的功能、而MySQL提供了一系列功能。它可以在笔记本电脑和台式机上充分运行。它可以轻松地适应环境、确保不会与现有Web服务器或应用程序发生相影响。
* *全面的事务处理支持。* MySQL是目前最强大的事务处理数据库引擎之一。它是实现完整数据完整性的解决方案、提供全面的原子、一致、隔离、持久的事务支持、多版本事务支持等功能； 和不受限制的行级锁定。它通过服务器强制引用完整性提供即时死锁标识。
* *数据安全。* MySQL以其最安全、最可靠的数据库管理系统而闻名全球、该系统用于常用的Web应用程序、如WordPress、DRUPAL、Joomla、Facebook、Google、 和Twitter。最新版本的MySQL提供的数据安全性和事务处理支持可以使任何企业受益、尤其是涉及频繁转账的电子商务企业。
* *可插拔架构。* MySQL可插拔存储引擎架构使数据库专业人员能够根据特定应用程序需求选择专用存储引擎，而无需管理应用程序编码要求。MySQL服务器架构可将应用程序编程人员和数据库管理员与存储级别的所有底层实施详细信息隔离开来、从而提供一致且简单的应用程序模型和API。尽管不同存储引擎的功能各不相同、但应用程序不会受到这些差异的影响。


如果您希望针对特定的应用程序需求(例如数据仓库、事务处理或HA情况)使用独立于任何一个存储引擎的接口和服务、MySQL高效的模块化架构可提供巨大的优势。
