---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/mc-mcc-nvfail.html 
keywords: oracle, metrocluster, extended rac, rac, nvfail, switchover 
summary: 基于MetroCluster的Oracle—NVFAIL 
---
= MetroCluster和NVFAIL
:allow-uri-read: 


[role="lead"]
NVFAIL是ONTAP中的一项常规数据完整性功能、对于数据库工作负载尤为重要、有关详细信息、请参见 link:../ontap-configuration/oracle_and_nvfail.html["NVFAIL"]。此外、对于NVFAIL、还需要考虑特定于MetroCluster的注意事项。



== 通过手动强制执行NVFAIL扩展RAC

要使用扩展RAC集群强制执行切换、最安全的方法是指定 `-force-nvfail-all` 在命令行中。此选项可作为紧急措施使用、以确保所有缓存数据均已转储。如果主机正在使用最初位于发生灾难的站点上的存储资源、则会收到I/O错误或陈旧的文件句柄 (`ESTALE`)错误。Oracle数据库崩溃、文件系统要么完全脱机、要么切换到只读模式。

切换完成后、 `in-nvfailed-state` 标记、并且LUN需要置于联机状态。完成此活动后、可以重新启动数据库。这些任务可以自动执行、以减少RTO。



== 使用dr-force -nvfail.扩展RAC

最安全的配置是设置 `dr-force-nvfail` 标记。因此、卷在进入后将不可用 `in-nvfailed-state` 切换期间。切换完成后、 `in-nvfailed-state` 标记、并且LUN必须置于联机状态。完成这些活动后、可以重新启动数据库。这些任务可以自动执行、以减少RTO。

其结果与使用类似 `-force-nvfail-all` 标志。但是、受影响的卷数量可以仅限于那些必须防止应用程序或具有陈旧缓存的操作系统访问的卷。



== 扩展RAC、不使用dr-force -nvfail

对于不使用的环境、有两个关键要求 `dr-force-nvfail` 在数据库卷上：

* 在主站点丢失后、强制切换的发生时间不得超过30秒。
* 在执行维护任务期间、或者在SyncMirror plexes或NVRAM复制不同步的任何其他情况下、都不能发生切换。可使用Tiebre可能性 软件满足第一个要求、该软件配置为在站点发生故障后30秒内执行切换。此要求并不意味着必须在检测到站点故障后30秒内执行切换。这确实意味着、如果自某个站点确认正常运行后30秒内已过、则不再安全地强制执行切换。


如果已知MetroCluster配置不同步、则可以通过禁用所有自动切换功能来部分满足第二项要求。更好的选择是、使用Tiebre机会 解决方案监控NVRAM复制和SyncMirror plexes的运行状况。如果集群未完全同步、则Tieb破碎 机不应触发切换。

NetApp MCTB软件无法监控同步状态、因此、如果MetroCluster因任何原因而不同步、则应将其禁用。ClusterLion具有NVRAM监控和丛监控功能、可以将其配置为不触发切换、除非确认MetroCluster系统已完全同步。
