---
sidebar: sidebar 
permalink: postgres/postgres-snapshot-dp.html 
keywords: PostgreSQL,database,postgres 
summary: PostgreSQL数据库和存储快照 
---
= PostgreSQL数据库和存储快照
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用PostgreSQL进行基于Snapshot的备份时、需要为数据文件、WAL文件和归档的WAL文件配置快照、以提供完整或时间点恢复。

对于PostgreSQL数据库、快照的平均备份时间介于几秒到几分钟之间。此备份速度比快60到100倍 `pg_basebackup` 以及其他基于文件系统的备份方法。

NetApp存储上的快照可以是崩溃状态一致的快照、也可以是应用程序一致的快照。系统会在存储上创建崩溃状态一致的快照、而不会使数据库处于静音状态、而是在数据库处于备份模式时创建应用程序一致的快照。NetApp还可确保后续快照是永久增量备份、以节省存储空间并提高网络效率。

由于快照速度快且不会影响系统性能、因此您可以计划每天创建多个快照、而不是像使用其他流式备份技术那样创建一个每日备份。在需要执行还原和恢复操作时、系统停机时间可通过以下两个主要功能来减少：

* NetApp SnapRestore数据恢复技术意味着只需几秒钟即可执行还原操作。
* 主动恢复点目标(Recovery Point目标、RPO)意味着、必须应用的数据库日志减少、并且前向恢复也会加快。


要备份PostgreSQL、必须确保数据卷同时受到(一致性组) WAL和归档日志的保护。在使用Snapshot技术复制WAL文件时、请确保运行 `pg_stop` 刷新必须归档的所有WAL条目。如果在还原期间刷新WAL条目、则只需停止数据库、卸载或删除现有数据目录、并对存储执行SnapRestore操作即可。还原完成后、您可以挂载系统并将其恢复到当前状态。对于时间点恢复、您还可以恢复WAL和归档日志；然后PostgreSQL确定最一致的点并自动恢复它。

一致性组是ONTAP中的一项功能、如果在一个实例或包含多个表空间的数据库中挂载了多个卷、则建议使用一致性组。一致性组快照可确保所有卷都分组在一起并受到保护。您可以从ONTAP系统管理器高效管理一致性组、甚至可以克隆一致性组以创建数据库的实例副本、用于测试或开发目的。
